const verbs = [
// HABLAR (to speak)
  { infinitive:"hablar", translation:"to speak", tense:"present",
    conjugations:{yo:"hablo", tú:"hablas", "él/ella/usted":"habla", nosotros:"hablamos", vosotros:"habláis", "ellos/ellas/ustedes":"hablan"}},
  { infinitive:"hablar", translation:"to speak", tense:"preterite",
    conjugations:{yo:"hablé", tú:"hablaste", "él/ella/usted":"habló", nosotros:"hablamos", vosotros:"hablasteis", "ellos/ellas/ustedes":"hablaron"}},
  { infinitive:"hablar", translation:"to speak", tense:"imperfect",
    conjugations:{yo:"hablaba", tú:"hablabas", "él/ella/usted":"hablaba", nosotros:"hablábamos", vosotros:"hablabais", "ellos/ellas/ustedes":"hablaban"}},
  { infinitive:"hablar", translation:"to speak", tense:"future",
    conjugations:{yo:"hablaré", tú:"hablarás", "él/ella/usted":"hablará", nosotros:"hablaremos", vosotros:"hablaréis", "ellos/ellas/ustedes":"hablarán"}},
  { infinitive:"hablar", translation:"to speak", tense:"conditional",
    conjugations:{yo:"hablaría", tú:"hablarías", "él/ella/usted":"hablaría", nosotros:"hablaríamos", vosotros:"hablaríais", "ellos/ellas/ustedes":"hablarían"}},
  { infinitive:"hablar", translation:"to speak", tense:"present perfect",
    conjugations:{yo:"he hablado", tú:"has hablado", "él/ella/usted":"ha hablado", nosotros:"hemos hablado", vosotros:"habéis hablado", "ellos/ellas/ustedes":"han hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"pluscuamperfecto",
    conjugations:{yo:"había hablado", tú:"habías hablado", "él/ella/usted":"había hablado", nosotros:"habíamos hablado", vosotros:"habíais hablado", "ellos/ellas/ustedes":"habían hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"future perfect",
    conjugations:{yo:"habré hablado", tú:"habrás hablado", "él/ella/usted":"habrá hablado", nosotros:"habremos hablado", vosotros:"habréis hablado", "ellos/ellas/ustedes":"habrán hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"conditional perfect",
    conjugations:{yo:"habría hablado", tú:"habrías hablado", "él/ella/usted":"habría hablado", nosotros:"habríamos hablado", vosotros:"habríais hablado", "ellos/ellas/ustedes":"habrían hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"present subjunctive",
    conjugations:{yo:"hable", tú:"hables", "él/ella/usted":"hable", nosotros:"hablemos", vosotros:"habléis", "ellos/ellas/ustedes":"hablen"}},
  { infinitive:"hablar", translation:"to speak", tense:"imperfect subjunctive",
    conjugations:{yo:"hablara", tú:"hablaras", "él/ella/usted":"hablara", nosotros:"habláramos", vosotros:"hablarais", "ellos/ellas/ustedes":"hablaran"}},
  { infinitive:"hablar", translation:"to speak", tense:"present perfect subjunctive",
    conjugations:{yo:"haya hablado", tú:"hayas hablado", "él/ella/usted":"haya hablado", nosotros:"hayamos hablado", vosotros:"hayáis hablado", "ellos/ellas/ustedes":"hayan hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera hablado", tú:"hubieras hablado", "él/ella/usted":"hubiera hablado", nosotros:"hubiéramos hablado", vosotros:"hubierais hablado", "ellos/ellas/ustedes":"hubieran hablado"}},

  // COMER (to eat)
  { infinitive:"comer", translation:"to eat", tense:"present",
    conjugations:{yo:"como", tú:"comes", "él/ella/usted":"come", nosotros:"comemos", vosotros:"coméis", "ellos/ellas/ustedes":"comen"}},
  { infinitive:"comer", translation:"to eat", tense:"preterite",
    conjugations:{yo:"comí", tú:"comiste", "él/ella/usted":"comió", nosotros:"comimos", vosotros:"comisteis", "ellos/ellas/ustedes":"comieron"}},
  { infinitive:"comer", translation:"to eat", tense:"imperfect",
    conjugations:{yo:"comía", tú:"comías", "él/ella/usted":"comía", nosotros:"comíamos", vosotros:"comíais", "ellos/ellas/ustedes":"comían"}},
  { infinitive:"comer", translation:"to eat", tense:"future",
    conjugations:{yo:"comeré", tú:"comerás", "él/ella/usted":"comerá", nosotros:"comeremos", vosotros:"comeréis", "ellos/ellas/ustedes":"comerán"}},
  { infinitive:"comer", translation:"to eat", tense:"conditional",
    conjugations:{yo:"comería", tú:"comerías", "él/ella/usted":"comería", nosotros:"comeríamos", vosotros:"comeríais", "ellos/ellas/ustedes":"comerían"}},
  { infinitive:"comer", translation:"to eat", tense:"present perfect",
    conjugations:{yo:"he comido", tú:"has comido", "él/ella/usted":"ha comido", nosotros:"hemos comido", vosotros:"habéis comido", "ellos/ellas/ustedes":"han comido"}},
  { infinitive:"comer", translation:"to eat", tense:"pluscuamperfecto",
    conjugations:{yo:"había comido", tú:"habías comido", "él/ella/usted":"había comido", nosotros:"habíamos comido", vosotros:"habíais comido", "ellos/ellas/ustedes":"habían comido"}},
  { infinitive:"comer", translation:"to eat", tense:"future perfect",
    conjugations:{yo:"habré comido", tú:"habrás comido", "él/ella/usted":"habrá comido", nosotros:"habremos comido", vosotros:"habréis comido", "ellos/ellas/ustedes":"habrán comido"}},
  { infinitive:"comer", translation:"to eat", tense:"conditional perfect",
    conjugations:{yo:"habría comido", tú:"habrías comido", "él/ella/usted":"habría comido", nosotros:"habríamos comido", vosotros:"habríais comido", "ellos/ellas/ustedes":"habrían comido"}},
  { infinitive:"comer", translation:"to eat", tense:"present subjunctive",
    conjugations:{yo:"coma", tú:"comas", "él/ella/usted":"coma", nosotros:"comamos", vosotros:"comáis", "ellos/ellas/ustedes":"coman"}},
  { infinitive:"comer", translation:"to eat", tense:"imperfect subjunctive",
    conjugations:{yo:"comiera", tú:"comieras", "él/ella/usted":"comiera", nosotros:"comiéramos", vosotros:"comierais", "ellos/ellas/ustedes":"comieran"}},
  { infinitive:"comer", translation:"to eat", tense:"present perfect subjunctive",
    conjugations:{yo:"haya comido", tú:"hayas comido", "él/ella/usted":"haya comido", nosotros:"hayamos comido", vosotros:"hayáis comido", "ellos/ellas/ustedes":"hayan comido"}},
  { infinitive:"comer", translation:"to eat", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera comido", tú:"hubieras comido", "él/ella/usted":"hubiera comido", nosotros:"hubiéramos comido", vosotros:"hubierais comido", "ellos/ellas/ustedes":"hubieran comido"}},

  // VIVIR (to live)
  { infinitive:"vivir", translation:"to live", tense:"present",
    conjugations:{yo:"vivo", tú:"vives", "él/ella/usted":"vive", nosotros:"vivimos", vosotros:"vivís", "ellos/ellas/ustedes":"viven"}},
  { infinitive:"vivir", translation:"to live", tense:"preterite",
    conjugations:{yo:"viví", tú:"viviste", "él/ella/usted":"vivió", nosotros:"vivimos", vosotros:"vivisteis", "ellos/ellas/ustedes":"vivieron"}},
  { infinitive:"vivir", translation:"to live", tense:"imperfect",
    conjugations:{yo:"vivía", tú:"vivías", "él/ella/usted":"vivía", nosotros:"vivíamos", vosotros:"vivíais", "ellos/ellas/ustedes":"vivían"}},
  { infinitive:"vivir", translation:"to live", tense:"future",
    conjugations:{yo:"viviré", tú:"vivirás", "él/ella/usted":"vivirá", nosotros:"viviremos", vosotros:"viviréis", "ellos/ellas/ustedes":"vivirán"}},
  { infinitive:"vivir", translation:"to live", tense:"conditional",
    conjugations:{yo:"viviría", tú:"vivirías", "él/ella/usted":"viviría", nosotros:"viviríamos", vosotros:"viviríais", "ellos/ellas/ustedes":"vivirían"}},
  { infinitive:"vivir", translation:"to live", tense:"present perfect",
    conjugations:{yo:"he vivido", tú:"has vivido", "él/ella/usted":"ha vivido", nosotros:"hemos vivido", vosotros:"habéis vivido", "ellos/ellas/ustedes":"han vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"pluscuamperfecto",
    conjugations:{yo:"había vivido", tú:"habías vivido", "él/ella/usted":"había vivido", nosotros:"habíamos vivido", vosotros:"habíais vivido", "ellos/ellas/ustedes":"habían vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"future perfect",
    conjugations:{yo:"habré vivido", tú:"habrás vivido", "él/ella/usted":"habrá vivido", nosotros:"habremos vivido", vosotros:"habréis vivido", "ellos/ellas/ustedes":"habrán vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"conditional perfect",
    conjugations:{yo:"habría vivido", tú:"habrías vivido", "él/ella/usted":"habría vivido", nosotros:"habríamos vivido", vosotros:"habríais vivido", "ellos/ellas/ustedes":"habrían vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"present subjunctive",
    conjugations:{yo:"viva", tú:"vivas", "él/ella/usted":"viva", nosotros:"vivamos", vosotros:"viváis", "ellos/ellas/ustedes":"vivan"}},
  { infinitive:"vivir", translation:"to live", tense:"imperfect subjunctive",
    conjugations:{yo:"viviera", tú:"vivieras", "él/ella/usted":"viviera", nosotros:"viviéramos", vosotros:"vivierais", "ellos/ellas/ustedes":"vivieran"}},
  { infinitive:"vivir", translation:"to live", tense:"present perfect subjunctive",
    conjugations:{yo:"haya vivido", tú:"hayas vivido", "él/ella/usted":"haya vivido", nosotros:"hayamos vivido", vosotros:"hayáis vivido", "ellos/ellas/ustedes":"hayan vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera vivido", tú:"hubieras vivido", "él/ella/usted":"hubiera vivido", nosotros:"hubiéramos vivido", vosotros:"hubierais vivido", "ellos/ellas/ustedes":"hubieran vivido"}},

    // SER (to be)
  { infinitive:"ser", translation:"to be", tense:"present",
    conjugations:{yo:"soy", tú:"eres", "él/ella/usted":"es", nosotros:"somos", vosotros:"sois", "ellos/ellas/ustedes":"son"}},
  { infinitive:"ser", translation:"to be", tense:"preterite",
    conjugations:{yo:"fui", tú:"fuiste", "él/ella/usted":"fue", nosotros:"fuimos", vosotros:"fuisteis", "ellos/ellas/ustedes":"fueron"}},
  { infinitive:"ser", translation:"to be", tense:"imperfect",
    conjugations:{yo:"era", tú:"eras", "él/ella/usted":"era", nosotros:"éramos", vosotros:"erais", "ellos/ellas/ustedes":"eran"}},
  { infinitive:"ser", translation:"to be", tense:"future",
    conjugations:{yo:"seré", tú:"serás", "él/ella/usted":"será", nosotros:"seremos", vosotros:"seréis", "ellos/ellas/ustedes":"serán"}},
  { infinitive:"ser", translation:"to be", tense:"conditional",
    conjugations:{yo:"sería", tú:"serías", "él/ella/usted":"sería", nosotros:"seríamos", vosotros:"seríais", "ellos/ellas/ustedes":"serían"}},
  { infinitive:"ser", translation:"to be", tense:"present perfect",
    conjugations:{yo:"he sido", tú:"has sido", "él/ella/usted":"ha sido", nosotros:"hemos sido", vosotros:"habéis sido", "ellos/ellas/ustedes":"han sido"}},
  { infinitive:"ser", translation:"to be", tense:"pluscuamperfecto",
    conjugations:{yo:"había sido", tú:"habías sido", "él/ella/usted":"había sido", nosotros:"habíamos sido", vosotros:"habíais sido", "ellos/ellas/ustedes":"habían sido"}},
  { infinitive:"ser", translation:"to be", tense:"future perfect",
    conjugations:{yo:"habré sido", tú:"habrás sido", "él/ella/usted":"habrá sido", nosotros:"habremos sido", vosotros:"habréis sido", "ellos/ellas/ustedes":"habrán sido"}},
  { infinitive:"ser", translation:"to be", tense:"conditional perfect",
    conjugations:{yo:"habría sido", tú:"habrías sido", "él/ella/usted":"habría sido", nosotros:"habríamos sido", vosotros:"habríais sido", "ellos/ellas/ustedes":"habrían sido"}},
  { infinitive:"ser", translation:"to be", tense:"present subjunctive",
    conjugations:{yo:"sea", tú:"seas", "él/ella/usted":"sea", nosotros:"seamos", vosotros:"seáis", "ellos/ellas/ustedes":"sean"}},
  { infinitive:"ser", translation:"to be", tense:"imperfect subjunctive",
    conjugations:{yo:"fuera", tú:"fueras", "él/ella/usted":"fuera", nosotros:"fuéramos", vosotros:"fuerais", "ellos/ellas/ustedes":"fueran"}},
  { infinitive:"ser", translation:"to be", tense:"present perfect subjunctive",
    conjugations:{yo:"haya sido", tú:"hayas sido", "él/ella/usted":"haya sido", nosotros:"hayamos sido", vosotros:"hayáis sido", "ellos/ellas/ustedes":"hayan sido"}},
  { infinitive:"ser", translation:"to be", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera sido", tú:"hubieras sido", "él/ella/usted":"hubiera sido", nosotros:"hubiéramos sido", vosotros:"hubierais sido", "ellos/ellas/ustedes":"hubieran sido"}},

  // ESTAR (to be)
  { infinitive:"estar", translation:"to be", tense:"present",
    conjugations:{yo:"estoy", tú:"estás", "él/ella/usted":"está", nosotros:"estamos", vosotros:"estáis", "ellos/ellas/ustedes":"están"}},
  { infinitive:"estar", translation:"to be", tense:"preterite",
    conjugations:{yo:"estuve", tú:"estuviste", "él/ella/usted":"estuvo", nosotros:"estuvimos", vosotros:"estuvisteis", "ellos/ellas/ustedes":"estuvieron"}},
  { infinitive:"estar", translation:"to be", tense:"imperfect",
    conjugations:{yo:"estaba", tú:"estabas", "él/ella/usted":"estaba", nosotros:"estábamos", vosotros:"estabais", "ellos/ellas/ustedes":"estaban"}},
  { infinitive:"estar", translation:"to be", tense:"future",
    conjugations:{yo:"estaré", tú:"estarás", "él/ella/usted":"estará", nosotros:"estaremos", vosotros:"estaréis", "ellos/ellas/ustedes":"estarán"}},
  { infinitive:"estar", translation:"to be", tense:"conditional",
    conjugations:{yo:"estaría", tú:"estarías", "él/ella/usted":"estaría", nosotros:"estaríamos", vosotros:"estaríais", "ellos/ellas/ustedes":"estarían"}},
  { infinitive:"estar", translation:"to be", tense:"present perfect",
    conjugations:{yo:"he estado", tú:"has estado", "él/ella/usted":"ha estado", nosotros:"hemos estado", vosotros:"habéis estado", "ellos/ellas/ustedes":"han estado"}},
  { infinitive:"estar", translation:"to be", tense:"pluscuamperfecto",
    conjugations:{yo:"había estado", tú:"habías estado", "él/ella/usted":"había estado", nosotros:"habíamos estado", vosotros:"habíais estado", "ellos/ellas/ustedes":"habían estado"}},
  { infinitive:"estar", translation:"to be", tense:"future perfect",
    conjugations:{yo:"habré estado", tú:"habrás estado", "él/ella/usted":"habrá estado", nosotros:"habremos estado", vosotros:"habréis estado", "ellos/ellas/ustedes":"habrán estado"}},
  { infinitive:"estar", translation:"to be", tense:"conditional perfect",
    conjugations:{yo:"habría estado", tú:"habrías estado", "él/ella/usted":"habría estado", nosotros:"habríamos estado", vosotros:"habríais estado", "ellos/ellas/ustedes":"habrían estado"}},
  { infinitive:"estar", translation:"to be", tense:"present subjunctive",
    conjugations:{yo:"esté", tú:"estés", "él/ella/usted":"esté", nosotros:"estemos", vosotros:"estéis", "ellos/ellas/ustedes":"estén"}},
  { infinitive:"estar", translation:"to be", tense:"imperfect subjunctive",
    conjugations:{yo:"estuviera", tú:"estuvieras", "él/ella/usted":"estuviera", nosotros:"estuviéramos", vosotros:"estuvierais", "ellos/ellas/ustedes":"estuvieran"}},
  { infinitive:"estar", translation:"to be", tense:"present perfect subjunctive",
    conjugations:{yo:"haya estado", tú:"hayas estado", "él/ella/usted":"haya estado", nosotros:"hayamos estado", vosotros:"hayáis estado", "ellos/ellas/ustedes":"hayan estado"}},
  { infinitive:"estar", translation:"to be", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera estado", tú:"hubieras estado", "él/ella/usted":"hubiera estado", nosotros:"hubiéramos estado", vosotros:"hubierais estado", "ellos/ellas/ustedes":"hubieran estado"}},

  // TENER (to have)
  { infinitive:"tener", translation:"to have", tense:"present",
    conjugations:{yo:"tengo", tú:"tienes", "él/ella/usted":"tiene", nosotros:"tenemos", vosotros:"tenéis", "ellos/ellas/ustedes":"tienen"}},
  { infinitive:"tener", translation:"to have", tense:"preterite",
    conjugations:{yo:"tuve", tú:"tuviste", "él/ella/usted":"tuvo", nosotros:"tuvimos", vosotros:"tuvisteis", "ellos/ellas/ustedes":"tuvieron"}},
  { infinitive:"tener", translation:"to have", tense:"imperfect",
    conjugations:{yo:"tenía", tú:"tenías", "él/ella/usted":"tenía", nosotros:"teníamos", vosotros:"teníais", "ellos/ellas/ustedes":"tenían"}},
  { infinitive:"tener", translation:"to have", tense:"future",
    conjugations:{yo:"tendré", tú:"tendrás", "él/ella/usted":"tendrá", nosotros:"tendremos", vosotros:"tendréis", "ellos/ellas/ustedes":"tendrán"}},
  { infinitive:"tener", translation:"to have", tense:"conditional",
    conjugations:{yo:"tendría", tú:"tendrías", "él/ella/usted":"tendría", nosotros:"tendríamos", vosotros:"tendríais", "ellos/ellas/ustedes":"tendrían"}},
  { infinitive:"tener", translation:"to have", tense:"present perfect",
    conjugations:{yo:"he tenido", tú:"has tenido", "él/ella/usted":"ha tenido", nosotros:"hemos tenido", vosotros:"habéis tenido", "ellos/ellas/ustedes":"han tenido"}},
  { infinitive:"tener", translation:"to have", tense:"pluscuamperfecto",
    conjugations:{yo:"había tenido", tú:"habías tenido", "él/ella/usted":"había tenido", nosotros:"habíamos tenido", vosotros:"habíais tenido", "ellos/ellas/ustedes":"habían tenido"}},
  { infinitive:"tener", translation:"to have", tense:"future perfect",
    conjugations:{yo:"habré tenido", tú:"habrás tenido", "él/ella/usted":"habrá tenido", nosotros:"habremos tenido", vosotros:"habréis tenido", "ellos/ellas/ustedes":"habrán tenido"}},
  { infinitive:"tener", translation:"to have", tense:"conditional perfect",
    conjugations:{yo:"habría tenido", tú:"habrías tenido", "él/ella/usted":"habría tenido", nosotros:"habríamos tenido", vosotros:"habríais tenido", "ellos/ellas/ustedes":"habrían tenido"}},
  { infinitive:"tener", translation:"to have", tense:"present subjunctive",
    conjugations:{yo:"tenga", tú:"tengas", "él/ella/usted":"tenga", nosotros:"tengamos", vosotros:"tengáis", "ellos/ellas/ustedes":"tengan"}},
  { infinitive:"tener", translation:"to have", tense:"imperfect subjunctive",
    conjugations:{yo:"tuviera", tú:"tuvieras", "él/ella/usted":"tuviera", nosotros:"tuviéramos", vosotros:"tuvierais", "ellos/ellas/ustedes":"tuvieran"}},
  { infinitive:"tener", translation:"to have", tense:"present perfect subjunctive",
    conjugations:{yo:"haya tenido", tú:"hayas tenido", "él/ella/usted":"haya tenido", nosotros:"hayamos tenido", vosotros:"hayáis tenido", "ellos/ellas/ustedes":"hayan tenido"}},
  { infinitive:"tener", translation:"to have", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera tenido", tú:"hubieras tenido", "él/ella/usted":"hubiera tenido", nosotros:"hubiéramos tenido", vosotros:"hubierais tenido", "ellos/ellas/ustedes":"hubieran tenido"}},

  // IR (to go)
  { infinitive:"ir", translation:"to go", tense:"present",
    conjugations:{yo:"voy", tú:"vas", "él/ella/usted":"va", nosotros:"vamos", vosotros:"vais", "ellos/ellas/ustedes":"van"}},
  { infinitive:"ir", translation:"to go", tense:"preterite",
    conjugations:{yo:"fui", tú:"fuiste", "él/ella/usted":"fue", nosotros:"fuimos", vosotros:"fuisteis", "ellos/ellas/ustedes":"fueron"}},
  { infinitive:"ir", translation:"to go", tense:"imperfect",
    conjugations:{yo:"iba", tú:"ibas", "él/ella/usted":"iba", nosotros:"íbamos", vosotros:"ibais", "ellos/ellas/ustedes":"iban"}},
  { infinitive:"ir", translation:"to go", tense:"future",
    conjugations:{yo:"iré", tú:"irás", "él/ella/usted":"irá", nosotros:"iremos", vosotros:"iréis", "ellos/ellas/ustedes":"irán"}},
  { infinitive:"ir", translation:"to go", tense:"conditional",
    conjugations:{yo:"iría", tú:"irías", "él/ella/usted":"iría", nosotros:"iríamos", vosotros:"iríais", "ellos/ellas/ustedes":"irían"}},
  { infinitive:"ir", translation:"to go", tense:"present perfect",
    conjugations:{yo:"he ido", tú:"has ido", "él/ella/usted":"ha ido", nosotros:"hemos ido", vosotros:"habéis ido", "ellos/ellas/ustedes":"han ido"}},
  { infinitive:"ir", translation:"to go", tense:"pluscuamperfecto",
    conjugations:{yo:"había ido", tú:"habías ido", "él/ella/usted":"había ido", nosotros:"habíamos ido", vosotros:"habíais ido", "ellos/ellas/ustedes":"habían ido"}},
  { infinitive:"ir", translation:"to go", tense:"future perfect",
    conjugations:{yo:"habré ido", tú:"habrás ido", "él/ella/usted":"habrá ido", nosotros:"habremos ido", vosotros:"habréis ido", "ellos/ellas/ustedes":"habrán ido"}},
  { infinitive:"ir", translation:"to go", tense:"conditional perfect",
    conjugations:{yo:"habría ido", tú:"habrías ido", "él/ella/usted":"habría ido", nosotros:"habríamos ido", vosotros:"habríais ido", "ellos/ellas/ustedes":"habrían ido"}},
  { infinitive:"ir", translation:"to go", tense:"present subjunctive",
    conjugations:{yo:"vaya", tú:"vayas", "él/ella/usted":"vaya", nosotros:"vayamos", vosotros:"vayáis", "ellos/ellas/ustedes":"vayan"}},
  { infinitive:"ir", translation:"to go", tense:"imperfect subjunctive",
    conjugations:{yo:"fuera", tú:"fueras", "él/ella/usted":"fuera", nosotros:"fuéramos", vosotros:"fuerais", "ellos/ellas/ustedes":"fueran"}},
  { infinitive:"ir", translation:"to go", tense:"present perfect subjunctive",
    conjugations:{yo:"haya ido", tú:"hayas ido", "él/ella/usted":"haya ido", nosotros:"hayamos ido", vosotros:"hayáis ido", "ellos/ellas/ustedes":"hayan ido"}},
  { infinitive:"ir", translation:"to go", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera ido", tú:"hubieras ido", "él/ella/usted":"hubiera ido", nosotros:"hubiéramos ido", vosotros:"hubierais ido", "ellos/ellas/ustedes":"hubieran ido"}},

  // HACER (to do/make)
  { infinitive:"hacer", translation:"to do/make", tense:"present",
    conjugations:{yo:"hago", tú:"haces", "él/ella/usted":"hace", nosotros:"hacemos", vosotros:"hacéis", "ellos/ellas/ustedes":"hacen"}},
  { infinitive:"hacer", translation:"to do/make", tense:"preterite",
    conjugations:{yo:"hice", tú:"hiciste", "él/ella/usted":"hizo", nosotros:"hicimos", vosotros:"hicisteis", "ellos/ellas/ustedes":"hicieron"}},
  { infinitive:"hacer", translation:"to do/make", tense:"imperfect",
    conjugations:{yo:"hacía", tú:"hacías", "él/ella/usted":"hacía", nosotros:"hacíamos", vosotros:"hacíais", "ellos/ellas/ustedes":"hacían"}},
  { infinitive:"hacer", translation:"to do/make", tense:"future",
    conjugations:{yo:"haré", tú:"harás", "él/ella/usted":"hará", nosotros:"haremos", vosotros:"haréis", "ellos/ellas/ustedes":"harán"}},
  { infinitive:"hacer", translation:"to do/make", tense:"conditional",
    conjugations:{yo:"haría", tú:"harías", "él/ella/usted":"haría", nosotros:"haríamos", vosotros:"haríais", "ellos/ellas/ustedes":"harían"}},
  { infinitive:"hacer", translation:"to do/make", tense:"present perfect",
    conjugations:{yo:"he hecho", tú:"has hecho", "él/ella/usted":"ha hecho", nosotros:"hemos hecho", vosotros:"habéis hecho", "ellos/ellas/ustedes":"han hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"pluscuamperfecto",
    conjugations:{yo:"había hecho", tú:"habías hecho", "él/ella/usted":"había hecho", nosotros:"habíamos hecho", vosotros:"habíais hecho", "ellos/ellas/ustedes":"habían hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"future perfect",
    conjugations:{yo:"habré hecho", tú:"habrás hecho", "él/ella/usted":"habrá hecho", nosotros:"habremos hecho", vosotros:"habréis hecho", "ellos/ellas/ustedes":"habrán hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"conditional perfect",
    conjugations:{yo:"habría hecho", tú:"habrías hecho", "él/ella/usted":"habría hecho", nosotros:"habríamos hecho", vosotros:"habríais hecho", "ellos/ellas/ustedes":"habrían hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"present subjunctive",
    conjugations:{yo:"haga", tú:"hagas", "él/ella/usted":"haga", nosotros:"hagamos", vosotros:"hagáis", "ellos/ellas/ustedes":"hagan"}},
  { infinitive:"hacer", translation:"to do/make", tense:"imperfect subjunctive",
    conjugations:{yo:"hiciera", tú:"hicieras", "él/ella/usted":"hiciera", nosotros:"hiciéramos", vosotros:"hicierais", "ellos/ellas/ustedes":"hicieran"}},
  { infinitive:"hacer", translation:"to do/make", tense:"present perfect subjunctive",
    conjugations:{yo:"haya hecho", tú:"hayas hecho", "él/ella/usted":"haya hecho", nosotros:"hayamos hecho", vosotros:"hayáis hecho", "ellos/ellas/ustedes":"hayan hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera hecho", tú:"hubieras hecho", "él/ella/usted":"hubiera hecho", nosotros:"hubiéramos hecho", vosotros:"hubierais hecho", "ellos/ellas/ustedes":"hubieran hecho"}},
//PODER
  { infinitive:"poder", translation:"to be able", tense:"present",
  conjugations:{yo:"puedo", tú:"puedes", "él/ella/usted":"puede", nosotros:"podemos", vosotros:"podéis", "ellos/ellas/ustedes":"pueden"}},
  { infinitive:"poder", translation:"to be able", tense:"preterite",
  conjugations:{yo:"pude", tú:"pudiste", "él/ella/usted":"pudo", nosotros:"pudimos", vosotros:"pudisteis", "ellos/ellas/ustedes":"pudieron"}},
  { infinitive:"poder", translation:"to be able", tense:"imperfect",
  conjugations:{yo:"podía", tú:"podías", "él/ella/usted":"podía", nosotros:"podíamos", vosotros:"podíais", "ellos/ellas/ustedes":"podían"}},
  { infinitive:"poder", translation:"to be able", tense:"future",
  conjugations:{yo:"podré", tú:"podrás", "él/ella/usted":"podrá", nosotros:"podremos", vosotros:"podréis", "ellos/ellas/ustedes":"podrán"}},
  { infinitive:"poder", translation:"to be able", tense:"conditional",
  conjugations:{yo:"podría", tú:"podrías", "él/ella/usted":"podría", nosotros:"podríamos", vosotros:"podríais", "ellos/ellas/ustedes":"podrían"}},
  { infinitive:"poder", translation:"to be able", tense:"present perfect",
  conjugations:{yo:"he podido", tú:"has podido", "él/ella/usted":"ha podido", nosotros:"hemos podido", vosotros:"habéis podido", "ellos/ellas/ustedes":"han podido"}},
  { infinitive:"poder", translation:"to be able", tense:"pluscuamperfecto",
  conjugations:{yo:"había podido", tú:"habías podido", "él/ella/usted":"había podido", nosotros:"habíamos podido", vosotros:"habíais podido", "ellos/ellas/ustedes":"habían podido"}},
  { infinitive:"poder", translation:"to be able", tense:"future perfect",
  conjugations:{yo:"habré podido", tú:"habrás podido", "él/ella/usted":"habrá podido", nosotros:"habremos podido", vosotros:"habréis podido", "ellos/ellas/ustedes":"habrán podido"}},
  { infinitive:"poder", translation:"to be able", tense:"conditional perfect",
  conjugations:{yo:"habría podido", tú:"habrías podido", "él/ella/usted":"habría podido", nosotros:"habríamos podido", vosotros:"habríais podido", "ellos/ellas/ustedes":"habrían podido"}},
  { infinitive:"poder", translation:"to be able", tense:"present subjunctive",
  conjugations:{yo:"pueda", tú:"puedas", "él/ella/usted":"pueda", nosotros:"podamos", vosotros:"podáis", "ellos/ellas/ustedes":"puedan"}},
  { infinitive:"poder", translation:"to be able", tense:"imperfect subjunctive",
  conjugations:{yo:"pudiera", tú:"pudieras", "él/ella/usted":"pudiera", nosotros:"pudiéramos", vosotros:"pudierais", "ellos/ellas/ustedes":"pudieran"}},
  { infinitive:"poder", translation:"to be able", tense:"present perfect subjunctive",
  conjugations:{yo:"haya podido", tú:"hayas podido", "él/ella/usted":"haya podido", nosotros:"hayamos podido", vosotros:"hayáis podido", "ellos/ellas/ustedes":"hayan podido"}},
  { infinitive:"poder", translation:"to be able", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera podido", tú:"hubieras podido", "él/ella/usted":"hubiera podido", nosotros:"hubiéramos podido", vosotros:"hubierais podido", "ellos/ellas/ustedes":"hubieran podido"}},

// DECIR (to say / tell)
  { infinitive:"decir", translation:"to say", tense:"present",
  conjugations:{yo:"digo", tú:"dices", "él/ella/usted":"dice", nosotros:"decimos", vosotros:"decís", "ellos/ellas/ustedes":"dicen"}},
  { infinitive:"decir", translation:"to say", tense:"preterite",
  conjugations:{yo:"dije", tú:"dijiste", "él/ella/usted":"dijo", nosotros:"dijimos", vosotros:"dijisteis", "ellos/ellas/ustedes":"dijeron"}},
  { infinitive:"decir", translation:"to say", tense:"imperfect",
  conjugations:{yo:"decía", tú:"decías", "él/ella/usted":"decía", nosotros:"decíamos", vosotros:"decíais", "ellos/ellas/ustedes":"decían"}},
  { infinitive:"decir", translation:"to say", tense:"future",
  conjugations:{yo:"diré", tú:"dirás", "él/ella/usted":"dirá", nosotros:"diremos", vosotros:"diréis", "ellos/ellas/ustedes":"dirán"}},
  { infinitive:"decir", translation:"to say", tense:"conditional",
  conjugations:{yo:"diría", tú:"dirías", "él/ella/usted":"diría", nosotros:"diríamos", vosotros:"diríais", "ellos/ellas/ustedes":"dirían"}},
  { infinitive:"decir", translation:"to say", tense:"present perfect",
  conjugations:{yo:"he dicho", tú:"has dicho", "él/ella/usted":"ha dicho", nosotros:"hemos dicho", vosotros:"habéis dicho", "ellos/ellas/ustedes":"han dicho"}},
  { infinitive:"decir", translation:"to say", tense:"pluscuamperfecto",
  conjugations:{yo:"había dicho", tú:"habías dicho", "él/ella/usted":"había dicho", nosotros:"habíamos dicho", vosotros:"habíais dicho", "ellos/ellas/ustedes":"habían dicho"}},
  { infinitive:"decir", translation:"to say", tense:"future perfect",
  conjugations:{yo:"habré dicho", tú:"habrás dicho", "él/ella/usted":"habrá dicho", nosotros:"habremos dicho", vosotros:"habréis dicho", "ellos/ellas/ustedes":"habrán dicho"}},
  { infinitive:"decir", translation:"to say", tense:"conditional perfect",
  conjugations:{yo:"habría dicho", tú:"habrías dicho", "él/ella/usted":"habría dicho", nosotros:"habríamos dicho", vosotros:"habríais dicho", "ellos/ellas/ustedes":"habrían dicho"}},
  { infinitive:"decir", translation:"to say", tense:"present subjunctive",
  conjugations:{yo:"diga", tú:"digas", "él/ella/usted":"diga", nosotros:"digamos", vosotros:"digáis", "ellos/ellas/ustedes":"digan"}},
  { infinitive:"decir", translation:"to say", tense:"imperfect subjunctive",
  conjugations:{yo:"dijera", tú:"dijeras", "él/ella/usted":"dijera", nosotros:"dijéramos", vosotros:"dijerais", "ellos/ellas/ustedes":"dijeran"}},
  { infinitive:"decir", translation:"to say", tense:"present perfect subjunctive",
  conjugations:{yo:"haya dicho", tú:"hayas dicho", "él/ella/usted":"haya dicho", nosotros:"hayamos dicho", vosotros:"hayáis dicho", "ellos/ellas/ustedes":"hayan dicho"}},
  { infinitive:"decir", translation:"to say", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera dicho", tú:"hubieras dicho", "él/ella/usted":"hubiera dicho", nosotros:"hubiéramos dicho", vosotros:"hubierais dicho", "ellos/ellas/ustedes":"hubieran dicho"}},

  // DAR (to give)
{ infinitive:"dar", translation:"to give", tense:"present",
  conjugations:{yo:"doy", tú:"das", "él/ella/usted":"da", nosotros:"damos", vosotros:"dais", "ellos/ellas/ustedes":"dan"}},
{ infinitive:"dar", translation:"to give", tense:"preterite",
  conjugations:{yo:"di", tú:"diste", "él/ella/usted":"dio", nosotros:"dimos", vosotros:"disteis", "ellos/ellas/ustedes":"dieron"}},
{ infinitive:"dar", translation:"to give", tense:"imperfect",
  conjugations:{yo:"daba", tú:"dabas", "él/ella/usted":"daba", nosotros:"dábamos", vosotros:"dabais", "ellos/ellas/ustedes":"daban"}},
{ infinitive:"dar", translation:"to give", tense:"future",
  conjugations:{yo:"daré", tú:"darás", "él/ella/usted":"dará", nosotros:"daremos", vosotros:"daréis", "ellos/ellas/ustedes":"darán"}},
{ infinitive:"dar", translation:"to give", tense:"conditional",
  conjugations:{yo:"daría", tú:"darías", "él/ella/usted":"daría", nosotros:"daríamos", vosotros:"daríais", "ellos/ellas/ustedes":"darían"}},
{ infinitive:"dar", translation:"to give", tense:"present perfect",
  conjugations:{yo:"he dado", tú:"has dado", "él/ella/usted":"ha dado", nosotros:"hemos dado", vosotros:"habéis dado", "ellos/ellas/ustedes":"han dado"}},
{ infinitive:"dar", translation:"to give", tense:"pluscuamperfecto",
  conjugations:{yo:"había dado", tú:"habías dado", "él/ella/usted":"había dado", nosotros:"habíamos dado", vosotros:"habíais dado", "ellos/ellas/ustedes":"habían dado"}},
{ infinitive:"dar", translation:"to give", tense:"future perfect",
  conjugations:{yo:"habré dado", tú:"habrás dado", "él/ella/usted":"habrá dado", nosotros:"habremos dado", vosotros:"habréis dado", "ellos/ellas/ustedes":"habrán dado"}},
{ infinitive:"dar", translation:"to give", tense:"conditional perfect",
  conjugations:{yo:"habría dado", tú:"habrías dado", "él/ella/usted":"habría dado", nosotros:"habríamos dado", vosotros:"habríais dado", "ellos/ellas/ustedes":"habrían dado"}},
{ infinitive:"dar", translation:"to give", tense:"present subjunctive",
  conjugations:{yo:"dé", tú:"des", "él/ella/usted":"dé", nosotros:"demos", vosotros:"deis", "ellos/ellas/ustedes":"den"}},
{ infinitive:"dar", translation:"to give", tense:"imperfect subjunctive",
  conjugations:{yo:"diera", tú:"dieras", "él/ella/usted":"diera", nosotros:"diéramos", vosotros:"dierais", "ellos/ellas/ustedes":"dieran"}},
{ infinitive:"dar", translation:"to give", tense:"present perfect subjunctive",
  conjugations:{yo:"haya dado", tú:"hayas dado", "él/ella/usted":"haya dado", nosotros:"hayamos dado", vosotros:"hayáis dado", "ellos/ellas/ustedes":"hayan dado"}},
{ infinitive:"dar", translation:"to give", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera dado", tú:"hubieras dado", "él/ella/usted":"hubiera dado", nosotros:"hubiéramos dado", vosotros:"hubierais dado", "ellos/ellas/ustedes":"hubieran dado"}},

  // SABER (to know)
{ infinitive:"saber", translation:"to know", tense:"present",
  conjugations:{yo:"sé", tú:"sabes", "él/ella/usted":"sabe", nosotros:"sabemos", vosotros:"sabéis", "ellos/ellas/ustedes":"saben"}},
{ infinitive:"saber", translation:"to know", tense:"preterite",
  conjugations:{yo:"supe", tú:"supiste", "él/ella/usted":"supo", nosotros:"supimos", vosotros:"supisteis", "ellos/ellas/ustedes":"supieron"}},
{ infinitive:"saber", translation:"to know", tense:"imperfect",
  conjugations:{yo:"sabía", tú:"sabías", "él/ella/usted":"sabía", nosotros:"sabíamos", vosotros:"sabíais", "ellos/ellas/ustedes":"sabían"}},
{ infinitive:"saber", translation:"to know", tense:"future",
  conjugations:{yo:"sabré", tú:"sabrás", "él/ella/usted":"sabrá", nosotros:"sabremos", vosotros:"sabréis", "ellos/ellas/ustedes":"sabrán"}},
{ infinitive:"saber", translation:"to know", tense:"conditional",
  conjugations:{yo:"sabría", tú:"sabrías", "él/ella/usted":"sabría", nosotros:"sabríamos", vosotros:"sabríais", "ellos/ellas/ustedes":"sabrían"}},
{ infinitive:"saber", translation:"to know", tense:"present perfect",
  conjugations:{yo:"he sabido", tú:"has sabido", "él/ella/usted":"ha sabido", nosotros:"hemos sabido", vosotros:"habéis sabido", "ellos/ellas/ustedes":"han sabido"}},
{ infinitive:"saber", translation:"to know", tense:"pluscuamperfecto",
  conjugations:{yo:"había sabido", tú:"habías sabido", "él/ella/usted":"había sabido", nosotros:"habíamos sabido", vosotros:"habíais sabido", "ellos/ellas/ustedes":"habían sabido"}},
{ infinitive:"saber", translation:"to know", tense:"future perfect",
  conjugations:{yo:"habré sabido", tú:"habrás sabido", "él/ella/usted":"habrá sabido", nosotros:"habremos sabido", vosotros:"habréis sabido", "ellos/ellas/ustedes":"habrán sabido"}},
{ infinitive:"saber", translation:"to know", tense:"conditional perfect",
  conjugations:{yo:"habría sabido", tú:"habrías sabido", "él/ella/usted":"habría sabido", nosotros:"habríamos sabido", vosotros:"habríais sabido", "ellos/ellas/ustedes":"habrían sabido"}},
{ infinitive:"saber", translation:"to know", tense:"present subjunctive",
  conjugations:{yo:"sepa", tú:"sepas", "él/ella/usted":"sepa", nosotros:"sepamos", vosotros:"sepáis", "ellos/ellas/ustedes":"sepan"}},
{ infinitive:"saber", translation:"to know", tense:"imperfect subjunctive",
  conjugations:{yo:"supiera", tú:"supieras", "él/ella/usted":"supiera", nosotros:"supiéramos", vosotros:"supierais", "ellos/ellas/ustedes":"supieran"}},
{ infinitive:"saber", translation:"to know", tense:"present perfect subjunctive",
  conjugations:{yo:"haya sabido", tú:"hayas sabido", "él/ella/usted":"haya sabido", nosotros:"hayamos sabido", vosotros:"hayáis sabido", "ellos/ellas/ustedes":"hayan sabido"}},
{ infinitive:"saber", translation:"to know", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera sabido", tú:"hubieras sabido", "él/ella/usted":"hubiera sabido", nosotros:"hubiéramos sabido", vosotros:"hubierais sabido", "ellos/ellas/ustedes":"hubieran sabido"}},

  // QUERER (to want / to love)
{ infinitive:"querer", translation:"to want", tense:"present",
  conjugations:{yo:"quiero", tú:"quieres", "él/ella/usted":"quiere", nosotros:"queremos", vosotros:"queréis", "ellos/ellas/ustedes":"quieren"}},
{ infinitive:"querer", translation:"to want", tense:"preterite",
  conjugations:{yo:"quise", tú:"quisiste", "él/ella/usted":"quiso", nosotros:"quisimos", vosotros:"quisisteis", "ellos/ellas/ustedes":"quisieron"}},
{ infinitive:"querer", translation:"to want", tense:"imperfect",
  conjugations:{yo:"quería", tú:"querías", "él/ella/usted":"quería", nosotros:"queríamos", vosotros:"queríais", "ellos/ellas/ustedes":"querían"}},
{ infinitive:"querer", translation:"to want", tense:"future",
  conjugations:{yo:"querré", tú:"querrás", "él/ella/usted":"querrá", nosotros:"querremos", vosotros:"querréis", "ellos/ellas/ustedes":"querrán"}},
{ infinitive:"querer", translation:"to want", tense:"conditional",
  conjugations:{yo:"querría", tú:"querrías", "él/ella/usted":"querría", nosotros:"querríamos", vosotros:"querríais", "ellos/ellas/ustedes":"querrían"}},
{ infinitive:"querer", translation:"to want", tense:"present perfect",
  conjugations:{yo:"he querido", tú:"has querido", "él/ella/usted":"ha querido", nosotros:"hemos querido", vosotros:"habéis querido", "ellos/ellas/ustedes":"han querido"}},
{ infinitive:"querer", translation:"to want", tense:"pluscuamperfecto",
  conjugations:{yo:"había querido", tú:"habías querido", "él/ella/usted":"había querido", nosotros:"habíamos querido", vosotros:"habíais querido", "ellos/ellas/ustedes":"habían querido"}},
{ infinitive:"querer", translation:"to want", tense:"future perfect",
  conjugations:{yo:"habré querido", tú:"habrás querido", "él/ella/usted":"habrá querido", nosotros:"habremos querido", vosotros:"habréis querido", "ellos/ellas/ustedes":"habrán querido"}},
{ infinitive:"querer", translation:"to want", tense:"conditional perfect",
  conjugations:{yo:"habría querido", tú:"habrías querido", "él/ella/usted":"habría querido", nosotros:"habríamos querido", vosotros:"habríais querido", "ellos/ellas/ustedes":"habrían querido"}},
{ infinitive:"querer", translation:"to want", tense:"present subjunctive",
  conjugations:{yo:"quiera", tú:"quieras", "él/ella/usted":"quiera", nosotros:"queramos", vosotros:"queráis", "ellos/ellas/ustedes":"quieran"}},
{ infinitive:"querer", translation:"to want", tense:"imperfect subjunctive",
  conjugations:{yo:"quisiera", tú:"quisieras", "él/ella/usted":"quisiera", nosotros:"quisiéramos", vosotros:"quisierais", "ellos/ellas/ustedes":"quisieran"}},
{ infinitive:"querer", translation:"to want", tense:"present perfect subjunctive",
  conjugations:{yo:"haya querido", tú:"hayas querido", "él/ella/usted":"haya querido", nosotros:"hayamos querido", vosotros:"hayáis querido", "ellos/ellas/ustedes":"hayan querido"}},
{ infinitive:"querer", translation:"to want", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera querido", tú:"hubieras querido", "él/ella/usted":"hubiera querido", nosotros:"hubiéramos querido", vosotros:"hubierais querido", "ellos/ellas/ustedes":"hubieran querido"}},

// VER (to see)
{ infinitive:"ver", translation:"to see", tense:"present",
  conjugations:{yo:"veo", tú:"ves", "él/ella/usted":"ve", nosotros:"vemos", vosotros:"veis", "ellos/ellas/ustedes":"ven"}},
{ infinitive:"ver", translation:"to see", tense:"preterite",
  conjugations:{yo:"vi", tú:"viste", "él/ella/usted":"vio", nosotros:"vimos", vosotros:"visteis", "ellos/ellas/ustedes":"vieron"}},
{ infinitive:"ver", translation:"to see", tense:"imperfect",
  conjugations:{yo:"veía", tú:"veías", "él/ella/usted":"veía", nosotros:"veíamos", vosotros:"veíais", "ellos/ellas/ustedes":"veían"}},
{ infinitive:"ver", translation:"to see", tense:"future",
  conjugations:{yo:"veré", tú:"verás", "él/ella/usted":"verá", nosotros:"veremos", vosotros:"veréis", "ellos/ellas/ustedes":"verán"}},
{ infinitive:"ver", translation:"to see", tense:"conditional",
  conjugations:{yo:"vería", tú:"verías", "él/ella/usted":"vería", nosotros:"veríamos", vosotros:"veríais", "ellos/ellas/ustedes":"verían"}},
{ infinitive:"ver", translation:"to see", tense:"present perfect",
  conjugations:{yo:"he visto", tú:"has visto", "él/ella/usted":"ha visto", nosotros:"hemos visto", vosotros:"habéis visto", "ellos/ellas/ustedes":"han visto"}},
{ infinitive:"ver", translation:"to see", tense:"pluscuamperfecto",
  conjugations:{yo:"había visto", tú:"habías visto", "él/ella/usted":"había visto", nosotros:"habíamos visto", vosotros:"habíais visto", "ellos/ellas/ustedes":"habían visto"}},
{ infinitive:"ver", translation:"to see", tense:"future perfect",
  conjugations:{yo:"habré visto", tú:"habrás visto", "él/ella/usted":"habrá visto", nosotros:"habremos visto", vosotros:"habréis visto", "ellos/ellas/ustedes":"habrán visto"}},
{ infinitive:"ver", translation:"to see", tense:"conditional perfect",
  conjugations:{yo:"habría visto", tú:"habrías visto", "él/ella/usted":"habría visto", nosotros:"habríamos visto", vosotros:"habríais visto", "ellos/ellas/ustedes":"habrían visto"}},
{ infinitive:"ver", translation:"to see", tense:"present subjunctive",
  conjugations:{yo:"vea", tú:"veas", "él/ella/usted":"vea", nosotros:"veamos", vosotros:"veáis", "ellos/ellas/ustedes":"vean"}},
{ infinitive:"ver", translation:"to see", tense:"imperfect subjunctive",
  conjugations:{yo:"viera", tú:"vieras", "él/ella/usted":"viera", nosotros:"viéramos", vosotros:"vierais", "ellos/ellas/ustedes":"vieran"}},
{ infinitive:"ver", translation:"to see", tense:"present perfect subjunctive",
  conjugations:{yo:"haya visto", tú:"hayas visto", "él/ella/usted":"haya visto", nosotros:"hayamos visto", vosotros:"hayáis visto", "ellos/ellas/ustedes":"hayan visto"}},
{ infinitive:"ver", translation:"to see", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera visto", tú:"hubieras visto", "él/ella/usted":"hubiera visto", nosotros:"hubiéramos visto", vosotros:"hubierais visto", "ellos/ellas/ustedes":"hubieran visto"}},

  // VENIR (to come)
{ infinitive:"venir", translation:"to come", tense:"present",
  conjugations:{yo:"vengo", tú:"vienes", "él/ella/usted":"viene", nosotros:"venimos", vosotros:"venís", "ellos/ellas/ustedes":"vienen"}},
{ infinitive:"venir", translation:"to come", tense:"preterite",
  conjugations:{yo:"vine", tú:"viniste", "él/ella/usted":"vino", nosotros:"vinimos", vosotros:"vinisteis", "ellos/ellas/ustedes":"vinieron"}},
{ infinitive:"venir", translation:"to come", tense:"imperfect",
  conjugations:{yo:"venía", tú:"venías", "él/ella/usted":"venía", nosotros:"veníamos", vosotros:"veníais", "ellos/ellas/ustedes":"venían"}},
{ infinitive:"venir", translation:"to come", tense:"future",
  conjugations:{yo:"vendré", tú:"vendrás", "él/ella/usted":"vendrá", nosotros:"vendremos", vosotros:"vendréis", "ellos/ellas/ustedes":"vendrán"}},
{ infinitive:"venir", translation:"to come", tense:"conditional",
  conjugations:{yo:"vendría", tú:"vendrías", "él/ella/usted":"vendría", nosotros:"vendríamos", vosotros:"vendríais", "ellos/ellas/ustedes":"vendrían"}},
{ infinitive:"venir", translation:"to come", tense:"present perfect",
  conjugations:{yo:"he venido", tú:"has venido", "él/ella/usted":"ha venido", nosotros:"hemos venido", vosotros:"habéis venido", "ellos/ellas/ustedes":"han venido"}},
{ infinitive:"venir", translation:"to come", tense:"pluscuamperfecto",
  conjugations:{yo:"había venido", tú:"habías venido", "él/ella/usted":"había venido", nosotros:"habíamos venido", vosotros:"habíais venido", "ellos/ellas/ustedes":"habían venido"}},
{ infinitive:"venir", translation:"to come", tense:"future perfect",
  conjugations:{yo:"habré venido", tú:"habrás venido", "él/ella/usted":"habrá venido", nosotros:"habremos venido", vosotros:"habréis venido", "ellos/ellas/ustedes":"habrán venido"}},
{ infinitive:"venir", translation:"to come", tense:"conditional perfect",
  conjugations:{yo:"habría venido", tú:"habrías venido", "él/ella/usted":"habría venido", nosotros:"habríamos venido", vosotros:"habríais venido", "ellos/ellas/ustedes":"habrían venido"}},
{ infinitive:"venir", translation:"to come", tense:"present subjunctive",
  conjugations:{yo:"venga", tú:"vengas", "él/ella/usted":"venga", nosotros:"vengamos", vosotros:"vengáis", "ellos/ellas/ustedes":"vengan"}},
{ infinitive:"venir", translation:"to come", tense:"imperfect subjunctive",
  conjugations:{yo:"viniera", tú:"vinieras", "él/ella/usted":"viniera", nosotros:"viniéramos", vosotros:"vinierais", "ellos/ellas/ustedes":"vinieran"}},
{ infinitive:"venir", translation:"to come", tense:"present perfect subjunctive",
  conjugations:{yo:"haya venido", tú:"hayas venido", "él/ella/usted":"haya venido", nosotros:"hayamos venido", vosotros:"hayáis venido", "ellos/ellas/ustedes":"hayan venido"}},
{ infinitive:"venir", translation:"to come", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera venido", tú:"hubieras venido", "él/ella/usted":"hubiera venido", nosotros:"hubiéramos venido", vosotros:"hubierais venido", "ellos/ellas/ustedes":"hubieran venido"}},

  // LLEVAR (to carry / to take)
{ infinitive:"llevar", translation:"to carry", tense:"present",
  conjugations:{yo:"llevo", tú:"llevas", "él/ella/usted":"lleva", nosotros:"llevamos", vosotros:"lleváis", "ellos/ellas/ustedes":"llevan"}},
{ infinitive:"llevar", translation:"to carry", tense:"preterite",
  conjugations:{yo:"llevé", tú:"llevaste", "él/ella/usted":"llevó", nosotros:"llevamos", vosotros:"llevasteis", "ellos/ellas/ustedes":"llevaron"}},
{ infinitive:"llevar", translation:"to carry", tense:"imperfect",
  conjugations:{yo:"llevaba", tú:"llevabas", "él/ella/usted":"llevaba", nosotros:"llevábamos", vosotros:"llevabais", "ellos/ellas/ustedes":"llevaban"}},
{ infinitive:"llevar", translation:"to carry", tense:"future",
  conjugations:{yo:"llevaré", tú:"llevarás", "él/ella/usted":"llevará", nosotros:"llevaremos", vosotros:"llevaréis", "ellos/ellas/ustedes":"llevarán"}},
{ infinitive:"llevar", translation:"to carry", tense:"conditional",
  conjugations:{yo:"llevaría", tú:"llevarías", "él/ella/usted":"llevaría", nosotros:"llevaríamos", vosotros:"llevaríais", "ellos/ellas/ustedes":"llevarían"}},
{ infinitive:"llevar", translation:"to carry", tense:"present perfect",
  conjugations:{yo:"he llevado", tú:"has llevado", "él/ella/usted":"ha llevado", nosotros:"hemos llevado", vosotros:"habéis llevado", "ellos/ellas/ustedes":"han llevado"}},
{ infinitive:"llevar", translation:"to carry", tense:"pluscuamperfecto",
  conjugations:{yo:"había llevado", tú:"habías llevado", "él/ella/usted":"había llevado", nosotros:"habíamos llevado", vosotros:"habíais llevado", "ellos/ellas/ustedes":"habían llevado"}},
{ infinitive:"llevar", translation:"to carry", tense:"future perfect",
  conjugations:{yo:"habré llevado", tú:"habrás llevado", "él/ella/usted":"habrá llevado", nosotros:"habremos llevado", vosotros:"habréis llevado", "ellos/ellas/ustedes":"habrán llevado"}},
{ infinitive:"llevar", translation:"to carry", tense:"conditional perfect",
  conjugations:{yo:"habría llevado", tú:"habrías llevado", "él/ella/usted":"habría llevado", nosotros:"habríamos llevado", vosotros:"habríais llevado", "ellos/ellas/ustedes":"habrían llevado"}},
{ infinitive:"llevar", translation:"to carry", tense:"present subjunctive",
  conjugations:{yo:"lleve", tú:"lleves", "él/ella/usted":"lleve", nosotros:"llevemos", vosotros:"llevéis", "ellos/ellas/ustedes":"lleven"}},
{ infinitive:"llevar", translation:"to carry", tense:"imperfect subjunctive",
  conjugations:{yo:"llevara", tú:"llevaras", "él/ella/usted":"llevara", nosotros:"lleváramos", vosotros:"llevarais", "ellos/ellas/ustedes":"llevaran"}},
{ infinitive:"llevar", translation:"to carry", tense:"present perfect subjunctive",
  conjugations:{yo:"haya llevado", tú:"hayas llevado", "él/ella/usted":"haya llevado", nosotros:"hayamos llevado", vosotros:"hayáis llevado", "ellos/ellas/ustedes":"hayan llevado"}},
{ infinitive:"llevar", translation:"to carry", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera llevado", tú:"hubieras llevado", "él/ella/usted":"hubiera llevado", nosotros:"hubiéramos llevado", vosotros:"hubierais llevado", "ellos/ellas/ustedes":"hubieran llevado"}},

  // DEJAR (to leave / to let)
{ infinitive:"dejar", translation:"to leave", tense:"present",
  conjugations:{yo:"dejo", tú:"dejas", "él/ella/usted":"deja", nosotros:"dejamos", vosotros:"dejáis", "ellos/ellas/ustedes":"dejan"}},
{ infinitive:"dejar", translation:"to leave", tense:"preterite",
  conjugations:{yo:"dejé", tú:"dejaste", "él/ella/usted":"dejó", nosotros:"dejamos", vosotros:"dejasteis", "ellos/ellas/ustedes":"dejaron"}},
{ infinitive:"dejar", translation:"to leave", tense:"imperfect",
  conjugations:{yo:"dejaba", tú:"dejabas", "él/ella/usted":"dejaba", nosotros:"dejábamos", vosotros:"dejabais", "ellos/ellas/ustedes":"dejaban"}},
{ infinitive:"dejar", translation:"to leave", tense:"future",
  conjugations:{yo:"dejaré", tú:"dejarás", "él/ella/usted":"dejará", nosotros:"dejaremos", vosotros:"dejaréis", "ellos/ellas/ustedes":"dejarán"}},
{ infinitive:"dejar", translation:"to leave", tense:"conditional",
  conjugations:{yo:"dejaría", tú:"dejarías", "él/ella/usted":"dejaría", nosotros:"dejaríamos", vosotros:"dejaríais", "ellos/ellas/ustedes":"dejarían"}},
{ infinitive:"dejar", translation:"to leave", tense:"present perfect",
  conjugations:{yo:"he dejado", tú:"has dejado", "él/ella/usted":"ha dejado", nosotros:"hemos dejado", vosotros:"habéis dejado", "ellos/ellas/ustedes":"han dejado"}},
{ infinitive:"dejar", translation:"to leave", tense:"pluscuamperfecto",
  conjugations:{yo:"había dejado", tú:"habías dejado", "él/ella/usted":"había dejado", nosotros:"habíamos dejado", vosotros:"habíais dejado", "ellos/ellas/ustedes":"habían dejado"}},
{ infinitive:"dejar", translation:"to leave", tense:"future perfect",
  conjugations:{yo:"habré dejado", tú:"habrás dejado", "él/ella/usted":"habrá dejado", nosotros:"habremos dejado", vosotros:"habréis dejado", "ellos/ellas/ustedes":"habrán dejado"}},
{ infinitive:"dejar", translation:"to leave", tense:"conditional perfect",
  conjugations:{yo:"habría dejado", tú:"habrías dejado", "él/ella/usted":"habría dejado", nosotros:"habríamos dejado", vosotros:"habríais dejado", "ellos/ellas/ustedes":"habrían dejado"}},
{ infinitive:"dejar", translation:"to leave", tense:"present subjunctive",
  conjugations:{yo:"deje", tú:"dejes", "él/ella/usted":"deje", nosotros:"dejemos", vosotros:"dejéis", "ellos/ellas/ustedes":"dejen"}},
{ infinitive:"dejar", translation:"to leave", tense:"imperfect subjunctive",
  conjugations:{yo:"dejara", tú:"dejaras", "él/ella/usted":"dejara", nosotros:"dejáramos", vosotros:"dejarais", "ellos/ellas/ustedes":"dejaran"}},
{ infinitive:"dejar", translation:"to leave", tense:"present perfect subjunctive",
  conjugations:{yo:"haya dejado", tú:"hayas dejado", "él/ella/usted":"haya dejado", nosotros:"hayamos dejado", vosotros:"hayáis dejado", "ellos/ellas/ustedes":"hayan dejado"}},
{ infinitive:"dejar", translation:"to leave", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera dejado", tú:"hubieras dejado", "él/ella/usted":"hubiera dejado", nosotros:"hubiéramos dejado", vosotros:"hubierais dejado", "ellos/ellas/ustedes":"hubieran dejado"}},

 // SEGUIR (to follow / to continue)
{ infinitive:"seguir", translation:"to follow", tense:"present",
  conjugations:{yo:"sigo", tú:"sigues", "él/ella/usted":"sigue", nosotros:"seguimos", vosotros:"seguís", "ellos/ellas/ustedes":"siguen"}},
{ infinitive:"seguir", translation:"to follow", tense:"preterite",
  conjugations:{yo:"seguí", tú:"seguiste", "él/ella/usted":"siguió", nosotros:"seguimos", vosotros:"seguisteis", "ellos/ellas/ustedes":"siguieron"}},
{ infinitive:"seguir", translation:"to follow", tense:"imperfect",
  conjugations:{yo:"seguía", tú:"seguías", "él/ella/usted":"seguía", nosotros:"seguíamos", vosotros:"seguíais", "ellos/ellas/ustedes":"seguían"}},
{ infinitive:"seguir", translation:"to follow", tense:"future",
  conjugations:{yo:"seguiré", tú:"seguirás", "él/ella/usted":"seguirá", nosotros:"seguiremos", vosotros:"seguiréis", "ellos/ellas/ustedes":"seguirán"}},
{ infinitive:"seguir", translation:"to follow", tense:"conditional",
  conjugations:{yo:"seguiría", tú:"seguirías", "él/ella/usted":"seguiría", nosotros:"seguiríamos", vosotros:"seguiríais", "ellos/ellas/ustedes":"seguirían"}},
{ infinitive:"seguir", translation:"to follow", tense:"present perfect",
  conjugations:{yo:"he seguido", tú:"has seguido", "él/ella/usted":"ha seguido", nosotros:"hemos seguido", vosotros:"habéis seguido", "ellos/ellas/ustedes":"han seguido"}},
{ infinitive:"seguir", translation:"to follow", tense:"pluscuamperfecto",
  conjugations:{yo:"había seguido", tú:"habías seguido", "él/ella/usted":"había seguido", nosotros:"habíamos seguido", vosotros:"habíais seguido", "ellos/ellas/ustedes":"habían seguido"}},
{ infinitive:"seguir", translation:"to follow", tense:"future perfect",
  conjugations:{yo:"habré seguido", tú:"habrás seguido", "él/ella/usted":"habrá seguido", nosotros:"habremos seguido", vosotros:"habréis seguido", "ellos/ellas/ustedes":"habrán seguido"}},
{ infinitive:"seguir", translation:"to follow", tense:"conditional perfect",
  conjugations:{yo:"habría seguido", tú:"habrías seguido", "él/ella/usted":"habría seguido", nosotros:"habríamos seguido", vosotros:"habríais seguido", "ellos/ellas/ustedes":"habrían seguido"}},
{ infinitive:"seguir", translation:"to follow", tense:"present subjunctive",
  conjugations:{yo:"siga", tú:"sigas", "él/ella/usted":"siga", nosotros:"sigamos", vosotros:"sigáis", "ellos/ellas/ustedes":"sigan"}},
{ infinitive:"seguir", translation:"to follow", tense:"imperfect subjunctive",
  conjugations:{yo:"siguiera", tú:"siguieras", "él/ella/usted":"siguiera", nosotros:"sigiéramos", vosotros:"siguierais", "ellos/ellas/ustedes":"siguieran"}},
{ infinitive:"seguir", translation:"to follow", tense:"present perfect subjunctive",
  conjugations:{yo:"haya seguido", tú:"hayas seguido", "él/ella/usted":"haya seguido", nosotros:"hayamos seguido", vosotros:"hayáis seguido", "ellos/ellas/ustedes":"hayan seguido"}},
{ infinitive:"seguir", translation:"to follow", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera seguido", tú:"hubieras seguido", "él/ella/usted":"hubiera seguido", nosotros:"hubiéramos seguido", vosotros:"hubierais seguido", "ellos/ellas/ustedes":"hubieran seguido"}},

  // ENCONTRAR (to find)
{ infinitive:"encontrar", translation:"to find", tense:"present",
  conjugations:{yo:"encuentro", tú:"encuentras", "él/ella/usted":"encuentra", nosotros:"encontramos", vosotros:"encontráis", "ellos/ellas/ustedes":"encuentran"}},
{ infinitive:"encontrar", translation:"to find", tense:"preterite",
  conjugations:{yo:"encontré", tú:"encontraste", "él/ella/usted":"encontró", nosotros:"encontramos", vosotros:"encontrasteis", "ellos/ellas/ustedes":"encontraron"}},
{ infinitive:"encontrar", translation:"to find", tense:"imperfect",
  conjugations:{yo:"encontraba", tú:"encontrabas", "él/ella/usted":"encontraba", nosotros:"encontrábamos", vosotros:"encontrabais", "ellos/ellas/ustedes":"encontraban"}},
{ infinitive:"encontrar", translation:"to find", tense:"future",
  conjugations:{yo:"encontraré", tú:"encontrarás", "él/ella/usted":"encontrará", nosotros:"encontraremos", vosotros:"encontraréis", "ellos/ellas/ustedes":"encontrarán"}},
{ infinitive:"encontrar", translation:"to find", tense:"conditional",
  conjugations:{yo:"encontraría", tú:"encontrarías", "él/ella/usted":"encontraría", nosotros:"encontraríamos", vosotros:"encontraríais", "ellos/ellas/ustedes":"encontrarían"}},
{ infinitive:"encontrar", translation:"to find", tense:"present perfect",
  conjugations:{yo:"he encontrado", tú:"has encontrado", "él/ella/usted":"ha encontrado", nosotros:"hemos encontrado", vosotros:"habéis encontrado", "ellos/ellas/ustedes":"han encontrado"}},
{ infinitive:"encontrar", translation:"to find", tense:"pluscuamperfecto",
  conjugations:{yo:"había encontrado", tú:"habías encontrado", "él/ella/usted":"había encontrado", nosotros:"habíamos encontrado", vosotros:"habíais encontrado", "ellos/ellas/ustedes":"habían encontrado"}},
{ infinitive:"encontrar", translation:"to find", tense:"future perfect",
  conjugations:{yo:"habré encontrado", tú:"habrás encontrado", "él/ella/usted":"habrá encontrado", nosotros:"habremos encontrado", vosotros:"habréis encontrado", "ellos/ellas/ustedes":"habrán encontrado"}},
{ infinitive:"encontrar", translation:"to find", tense:"conditional perfect",
  conjugations:{yo:"habría encontrado", tú:"habrías encontrado", "él/ella/usted":"habría encontrado", nosotros:"habríamos encontrado", vosotros:"habríais encontrado", "ellos/ellas/ustedes":"habrían encontrado"}},
{ infinitive:"encontrar", translation:"to find", tense:"present subjunctive",
  conjugations:{yo:"encuentre", tú:"encuentres", "él/ella/usted":"encuentre", nosotros:"encontremos", vosotros:"encontréis", "ellos/ellas/ustedes":"encuentren"}},
{ infinitive:"encontrar", translation:"to find", tense:"imperfect subjunctive",
  conjugations:{yo:"encontrara", tú:"encontraras", "él/ella/usted":"encontrara", nosotros:"encontráramos", vosotros:"encontrarais", "ellos/ellas/ustedes":"encontraran"}},
{ infinitive:"encontrar", translation:"to find", tense:"present perfect subjunctive",
  conjugations:{yo:"haya encontrado", tú:"hayas encontrado", "él/ella/usted":"haya encontrado", nosotros:"hayamos encontrado", vosotros:"hayáis encontrado", "ellos/ellas/ustedes":"hayan encontrado"}},
{ infinitive:"encontrar", translation:"to find", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera encontrado", tú:"hubieras encontrado", "él/ella/usted":"hubiera encontrado", nosotros:"hubiéramos encontrado", vosotros:"hubierais encontrado", "ellos/ellas/ustedes":"hubieran encontrado"}},

  // PONER (to put / to place)
{ infinitive:"poner", translation:"to put", tense:"present",
  conjugations:{yo:"pongo", tú:"pones", "él/ella/usted":"pone", nosotros:"ponemos", vosotros:"ponéis", "ellos/ellas/ustedes":"ponen"}},
{ infinitive:"poner", translation:"to put", tense:"preterite",
  conjugations:{yo:"puse", tú:"pusiste", "él/ella/usted":"puso", nosotros:"pusimos", vosotros:"pusisteis", "ellos/ellas/ustedes":"pusieron"}},
{ infinitive:"poner", translation:"to put", tense:"imperfect",
  conjugations:{yo:"ponía", tú:"ponías", "él/ella/usted":"ponía", nosotros:"poníamos", vosotros:"poníais", "ellos/ellas/ustedes":"ponían"}},
{ infinitive:"poner", translation:"to put", tense:"future",
  conjugations:{yo:"pondré", tú:"pondrás", "él/ella/usted":"pondrá", nosotros:"pondremos", vosotros:"pondréis", "ellos/ellas/ustedes":"pondrán"}},
{ infinitive:"poner", translation:"to put", tense:"conditional",
  conjugations:{yo:"pondría", tú:"pondrías", "él/ella/usted":"pondría", nosotros:"pondríamos", vosotros:"pondríais", "ellos/ellas/ustedes":"pondrían"}},
{ infinitive:"poner", translation:"to put", tense:"present perfect",
  conjugations:{yo:"he puesto", tú:"has puesto", "él/ella/usted":"ha puesto", nosotros:"hemos puesto", vosotros:"habéis puesto", "ellos/ellas/ustedes":"han puesto"}},
{ infinitive:"poner", translation:"to put", tense:"pluscuamperfecto",
  conjugations:{yo:"había puesto", tú:"habías puesto", "él/ella/usted":"había puesto", nosotros:"habíamos puesto", vosotros:"habíais puesto", "ellos/ellas/ustedes":"habían puesto"}},
{ infinitive:"poner", translation:"to put", tense:"future perfect",
  conjugations:{yo:"habré puesto", tú:"habrás puesto", "él/ella/usted":"habrá puesto", nosotros:"habremos puesto", vosotros:"habréis puesto", "ellos/ellas/ustedes":"habrán puesto"}},
{ infinitive:"poner", translation:"to put", tense:"conditional perfect",
  conjugations:{yo:"habría puesto", tú:"habrías puesto", "él/ella/usted":"habría puesto", nosotros:"habríamos puesto", vosotros:"habríais puesto", "ellos/ellas/ustedes":"habrían puesto"}},
{ infinitive:"poner", translation:"to put", tense:"present subjunctive",
  conjugations:{yo:"ponga", tú:"pongas", "él/ella/usted":"ponga", nosotros:"pongamos", vosotros:"pongáis", "ellos/ellas/ustedes":"pongan"}},
{ infinitive:"poner", translation:"to put", tense:"imperfect subjunctive",
  conjugations:{yo:"pusiera", tú:"pusieras", "él/ella/usted":"pusiera", nosotros:"pusiéramos", vosotros:"pusierais", "ellos/ellas/ustedes":"pusieran"}},
{ infinitive:"poner", translation:"to put", tense:"present perfect subjunctive",
  conjugations:{yo:"haya puesto", tú:"hayas puesto", "él/ella/usted":"haya puesto", nosotros:"hayamos puesto", vosotros:"hayáis puesto", "ellos/ellas/ustedes":"hayan puesto"}},
{ infinitive:"poner", translation:"to put", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera puesto", tú:"hubieras puesto", "él/ella/usted":"hubiera puesto", nosotros:"hubiéramos puesto", vosotros:"hubierais puesto", "ellos/ellas/ustedes":"hubieran puesto"}},

  
  // QUEDAR(SE) (to stay / to remain)
{ infinitive:"quedarse", translation:"to stay", tense:"present",
  conjugations:{yo:"me quedo", tú:"te quedas", "él/ella/usted":"se queda", nosotros:"nos quedamos", vosotros:"os quedáis", "ellos/ellas/ustedes":"se quedan"}},
{ infinitive:"quedarse", translation:"to stay", tense:"preterite",
  conjugations:{yo:"me quedé", tú:"te quedaste", "él/ella/usted":"se quedó", nosotros:"nos quedamos", vosotros:"os quedasteis", "ellos/ellas/ustedes":"se quedaron"}},
{ infinitive:"quedarse", translation:"to stay", tense:"imperfect",
  conjugations:{yo:"me quedaba", tú:"te quedabas", "él/ella/usted":"se quedaba", nosotros:"nos quedábamos", vosotros:"os quedabais", "ellos/ellas/ustedes":"se quedaban"}},
{ infinitive:"quedarse", translation:"to stay", tense:"future",
  conjugations:{yo:"me quedaré", tú:"te quedarás", "él/ella/usted":"se quedará", nosotros:"nos quedaremos", vosotros:"os quedaréis", "ellos/ellas/ustedes":"se quedarán"}},
{ infinitive:"quedarse", translation:"to stay", tense:"conditional",
  conjugations:{yo:"me quedaría", tú:"te quedarías", "él/ella/usted":"se quedaría", nosotros:"nos quedaríamos", vosotros:"os quedaríais", "ellos/ellas/ustedes":"se quedarían"}},
{ infinitive:"quedarse", translation:"to stay", tense:"present perfect",
  conjugations:{yo:"me he quedado", tú:"te has quedado", "él/ella/usted":"se ha quedado", nosotros:"nos hemos quedado", vosotros:"os habéis quedado", "ellos/ellas/ustedes":"se han quedado"}},
{ infinitive:"quedarse", translation:"to stay", tense:"pluscuamperfecto",
  conjugations:{yo:"me había quedado", tú:"te habías quedado", "él/ella/usted":"se había quedado", nosotros:"nos habíamos quedado", vosotros:"os habíais quedado", "ellos/ellas/ustedes":"se habían quedado"}},
{ infinitive:"quedarse", translation:"to stay", tense:"future perfect",
  conjugations:{yo:"me habré quedado", tú:"te habrás quedado", "él/ella/usted":"se habrá quedado", nosotros:"nos habremos quedado", vosotros:"os habréis quedado", "ellos/ellas/ustedes":"se habrán quedado"}},
{ infinitive:"quedarse", translation:"to stay", tense:"conditional perfect",
  conjugations:{yo:"me habría quedado", tú:"te habrías quedado", "él/ella/usted":"se habría quedado", nosotros:"nos habríamos quedado", vosotros:"os habríais quedado", "ellos/ellas/ustedes":"se habrían quedado"}},
{ infinitive:"quedarse", translation:"to stay", tense:"present subjunctive",
  conjugations:{yo:"me quede", tú:"te quedes", "él/ella/usted":"se quede", nosotros:"nos quedemos", vosotros:"os quedéis", "ellos/ellas/ustedes":"se queden"}},
{ infinitive:"quedarse", translation:"to stay", tense:"imperfect subjunctive",
  conjugations:{yo:"me quedara", tú:"te quedaras", "él/ella/usted":"se quedara", nosotros:"nos quedáramos", vosotros:"os quedarais", "ellos/ellas/ustedes":"se quedaran"}},
{ infinitive:"quedarse", translation:"to stay", tense:"present perfect subjunctive",
  conjugations:{yo:"me haya quedado", tú:"te hayas quedado", "él/ella/usted":"se haya quedado", nosotros:"nos hayamos quedado", vosotros:"os hayáis quedado", "ellos/ellas/ustedes":"se hayan quedado"}},
{ infinitive:"quedarse", translation:"to stay", tense:"past perfect subjunctive",
  conjugations:{yo:"me hubiera quedado", tú:"te hubieras quedado", "él/ella/usted":"se hubiera quedado", nosotros:"nos hubiéramos quedado", vosotros:"os hubierais quedado", "ellos/ellas/ustedes":"se hubieran quedado"}},

  // LLEGAR (to arrive)
{ infinitive:"llegar", translation:"to arrive", tense:"present",
  conjugations:{yo:"llego", tú:"llegas", "él/ella/usted":"llega", nosotros:"llegamos", vosotros:"llegáis", "ellos/ellas/ustedes":"llegan"}},
{ infinitive:"llegar", translation:"to arrive", tense:"preterite",
  conjugations:{yo:"llegué", tú:"llegaste", "él/ella/usted":"llegó", nosotros:"llegamos", vosotros:"llegasteis", "ellos/ellas/ustedes":"llegaron"}},
{ infinitive:"llegar", translation:"to arrive", tense:"imperfect",
  conjugations:{yo:"llegaba", tú:"llegabas", "él/ella/usted":"llegaba", nosotros:"llegábamos", vosotros:"llegabais", "ellos/ellas/ustedes":"llegaban"}},
{ infinitive:"llegar", translation:"to arrive", tense:"future",
  conjugations:{yo:"llegaré", tú:"llegarás", "él/ella/usted":"llegará", nosotros:"llegaremos", vosotros:"llegaréis", "ellos/ellas/ustedes":"llegarán"}},
{ infinitive:"llegar", translation:"to arrive", tense:"conditional",
  conjugations:{yo:"llegaría", tú:"llegarías", "él/ella/usted":"llegaría", nosotros:"llegaríamos", vosotros:"llegaríais", "ellos/ellas/ustedes":"llegarían"}},
{ infinitive:"llegar", translation:"to arrive", tense:"present perfect",
  conjugations:{yo:"he llegado", tú:"has llegado", "él/ella/usted":"ha llegado", nosotros:"hemos llegado", vosotros:"habéis llegado", "ellos/ellas/ustedes":"han llegado"}},
{ infinitive:"llegar", translation:"to arrive", tense:"pluscuamperfecto",
  conjugations:{yo:"había llegado", tú:"habías llegado", "él/ella/usted":"había llegado", nosotros:"habíamos llegado", vosotros:"habíais llegado", "ellos/ellas/ustedes":"habían llegado"}},
{ infinitive:"llegar", translation:"to arrive", tense:"future perfect",
  conjugations:{yo:"habré llegado", tú:"habrás llegado", "él/ella/usted":"habrá llegado", nosotros:"habremos llegado", vosotros:"habréis llegado", "ellos/ellas/ustedes":"habrán llegado"}},
{ infinitive:"llegar", translation:"to arrive", tense:"conditional perfect",
  conjugations:{yo:"habría llegado", tú:"habrías llegado", "él/ella/usted":"habría llegado", nosotros:"habríamos llegado", vosotros:"habríais llegado", "ellos/ellas/ustedes":"habrían llegado"}},
{ infinitive:"llegar", translation:"to arrive", tense:"present subjunctive",
  conjugations:{yo:"llegue", tú:"llegues", "él/ella/usted":"llegue", nosotros:"lleguemos", vosotros:"lleguéis", "ellos/ellas/ustedes":"lleguen"}},
{ infinitive:"llegar", translation:"to arrive", tense:"imperfect subjunctive",
  conjugations:{yo:"llegara", tú:"llegaras", "él/ella/usted":"llegara", nosotros:"llegáramos", vosotros:"llegarais", "ellos/ellas/ustedes":"llegaran"}},
{ infinitive:"llegar", translation:"to arrive", tense:"present perfect subjunctive",
  conjugations:{yo:"haya llegado", tú:"hayas llegado", "él/ella/usted":"haya llegado", nosotros:"hayamos llegado", vosotros:"hayáis llegado", "ellos/ellas/ustedes":"hayan llegado"}},
{ infinitive:"llegar", translation:"to arrive", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera llegado", tú:"hubieras llegado", "él/ella/usted":"hubiera llegado", nosotros:"hubiéramos llegado", vosotros:"hubierais llegado", "ellos/ellas/ustedes":"hubieran llegado"}},

  // CREER (to believe)
{ infinitive:"creer", translation:"to believe", tense:"present",
  conjugations:{yo:"creo", tú:"crees", "él/ella/usted":"cree", nosotros:"creemos", vosotros:"creéis", "ellos/ellas/ustedes":"creen"}},
{ infinitive:"creer", translation:"to believe", tense:"preterite",
  conjugations:{yo:"creí", tú:"creíste", "él/ella/usted":"creyó", nosotros:"creímos", vosotros:"creísteis", "ellos/ellas/ustedes":"creyeron"}},
{ infinitive:"creer", translation:"to believe", tense:"imperfect",
  conjugations:{yo:"creía", tú:"creías", "él/ella/usted":"creía", nosotros:"creíamos", vosotros:"creíais", "ellos/ellas/ustedes":"creían"}},
{ infinitive:"creer", translation:"to believe", tense:"future",
  conjugations:{yo:"creeré", tú:"creerás", "él/ella/usted":"creerá", nosotros:"creeremos", vosotros:"creeréis", "ellos/ellas/ustedes":"creerán"}},
{ infinitive:"creer", translation:"to believe", tense:"conditional",
  conjugations:{yo:"creería", tú:"creerías", "él/ella/usted":"creería", nosotros:"creeríamos", vosotros:"creeríais", "ellos/ellas/ustedes":"creerían"}},
{ infinitive:"creer", translation:"to believe", tense:"present perfect",
  conjugations:{yo:"he creído", tú:"has creído", "él/ella/usted":"ha creído", nosotros:"hemos creído", vosotros:"habéis creído", "ellos/ellas/ustedes":"han creído"}},
{ infinitive:"creer", translation:"to believe", tense:"pluscuamperfecto",
  conjugations:{yo:"había creído", tú:"habías creído", "él/ella/usted":"había creído", nosotros:"habíamos creído", vosotros:"habíais creído", "ellos/ellas/ustedes":"habían creído"}},
{ infinitive:"creer", translation:"to believe", tense:"future perfect",
  conjugations:{yo:"habré creído", tú:"habrás creído", "él/ella/usted":"habrá creído", nosotros:"habremos creído", vosotros:"habréis creído", "ellos/ellas/ustedes":"habrán creído"}},
{ infinitive:"creer", translation:"to believe", tense:"conditional perfect",
  conjugations:{yo:"habría creído", tú:"habrías creído", "él/ella/usted":"habría creído", nosotros:"habríamos creído", vosotros:"habríais creído", "ellos/ellas/ustedes":"habrían creído"}},
{ infinitive:"creer", translation:"to believe", tense:"present subjunctive",
  conjugations:{yo:"crea", tú:"creas", "él/ella/usted":"crea", nosotros:"creamos", vosotros:"creáis", "ellos/ellas/ustedes":"crean"}},
{ infinitive:"creer", translation:"to believe", tense:"imperfect subjunctive",
  conjugations:{yo:"creyera", tú:"creyeras", "él/ella/usted":"creyera", nosotros:"creyéramos", vosotros:"creyerais", "ellos/ellas/ustedes":"creyeran"}},
{ infinitive:"creer", translation:"to believe", tense:"present perfect subjunctive",
  conjugations:{yo:"haya creído", tú:"hayas creído", "él/ella/usted":"haya creído", nosotros:"hayamos creído", vosotros:"hayáis creído", "ellos/ellas/ustedes":"hayan creído"}},
{ infinitive:"creer", translation:"to believe", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera creído", tú:"hubieras creído", "él/ella/usted":"hubiera creído", nosotros:"hubiéramos creído", vosotros:"hubierais creído", "ellos/ellas/ustedes":"hubieran creído"}},

  // PASAR (to pass / to happen)
{ infinitive:"pasar", translation:"to pass", tense:"present",
  conjugations:{yo:"paso", tú:"pasas", "él/ella/usted":"pasa", nosotros:"pasamos", vosotros:"pasáis", "ellos/ellas/ustedes":"pasan"}},
{ infinitive:"pasar", translation:"to pass", tense:"preterite",
  conjugations:{yo:"pasé", tú:"pasaste", "él/ella/usted":"pasó", nosotros:"pasamos", vosotros:"pasasteis", "ellos/ellas/ustedes":"pasaron"}},
{ infinitive:"pasar", translation:"to pass", tense:"imperfect",
  conjugations:{yo:"pasaba", tú:"pasabas", "él/ella/usted":"pasaba", nosotros:"pasábamos", vosotros:"pasabais", "ellos/ellas/ustedes":"pasaban"}},
{ infinitive:"pasar", translation:"to pass", tense:"future",
  conjugations:{yo:"pasaré", tú:"pasarás", "él/ella/usted":"pasará", nosotros:"pasaremos", vosotros:"pasaréis", "ellos/ellas/ustedes":"pasarán"}},
{ infinitive:"pasar", translation:"to pass", tense:"conditional",
  conjugations:{yo:"pasaría", tú:"pasarías", "él/ella/usted":"pasaría", nosotros:"pasaríamos", vosotros:"pasaríais", "ellos/ellas/ustedes":"pasarían"}},
{ infinitive:"pasar", translation:"to pass", tense:"present perfect",
  conjugations:{yo:"he pasado", tú:"has pasado", "él/ella/usted":"ha pasado", nosotros:"hemos pasado", vosotros:"habéis pasado", "ellos/ellas/ustedes":"han pasado"}},
{ infinitive:"pasar", translation:"to pass", tense:"pluscuamperfecto",
  conjugations:{yo:"había pasado", tú:"habías pasado", "él/ella/usted":"había pasado", nosotros:"habíamos pasado", vosotros:"habíais pasado", "ellos/ellas/ustedes":"habían pasado"}},
{ infinitive:"pasar", translation:"to pass", tense:"future perfect",
  conjugations:{yo:"habré pasado", tú:"habrás pasado", "él/ella/usted":"habrá pasado", nosotros:"habremos pasado", vosotros:"habréis pasado", "ellos/ellas/ustedes":"habrán pasado"}},
{ infinitive:"pasar", translation:"to pass", tense:"conditional perfect",
  conjugations:{yo:"habría pasado", tú:"habrías pasado", "él/ella/usted":"habría pasado", nosotros:"habríamos pasado", vosotros:"habríais pasado", "ellos/ellas/ustedes":"habrían pasado"}},
{ infinitive:"pasar", translation:"to pass", tense:"present subjunctive",
  conjugations:{yo:"pase", tú:"pases", "él/ella/usted":"pase", nosotros:"pasemos", vosotros:"paséis", "ellos/ellas/ustedes":"pasen"}},
{ infinitive:"pasar", translation:"to pass", tense:"imperfect subjunctive",
  conjugations:{yo:"pasara", tú:"pasaras", "él/ella/usted":"pasara", nosotros:"pasáramos", vosotros:"pasarais", "ellos/ellas/ustedes":"pasaran"}},
{ infinitive:"pasar", translation:"to pass", tense:"present perfect subjunctive",
  conjugations:{yo:"haya pasado", tú:"hayas pasado", "él/ella/usted":"haya pasado", nosotros:"hayamos pasado", vosotros:"hayáis pasado", "ellos/ellas/ustedes":"hayan pasado"}},
{ infinitive:"pasar", translation:"to pass", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera pasado", tú:"hubieras pasado", "él/ella/usted":"hubiera pasado", nosotros:"hubiéramos pasado", vosotros:"hubierais pasado", "ellos/ellas/ustedes":"hubieran pasado"}},

  // PENSAR (to think)
{ infinitive:"pensar", translation:"to think", tense:"present",
  conjugations:{yo:"pienso", tú:"piensas", "él/ella/usted":"piensa", nosotros:"pensamos", vosotros:"pensáis", "ellos/ellas/ustedes":"piensan"}},
{ infinitive:"pensar", translation:"to think", tense:"preterite",
  conjugations:{yo:"pensé", tú:"pensaste", "él/ella/usted":"pensó", nosotros:"pensamos", vosotros:"pensasteis", "ellos/ellas/ustedes":"pensaron"}},
{ infinitive:"pensar", translation:"to think", tense:"imperfect",
  conjugations:{yo:"pensaba", tú:"pensabas", "él/ella/usted":"pensaba", nosotros:"pensábamos", vosotros:"pensabais", "ellos/ellas/ustedes":"pensaban"}},
{ infinitive:"pensar", translation:"to think", tense:"future",
  conjugations:{yo:"pensaré", tú:"pensarás", "él/ella/usted":"pensará", nosotros:"pensaremos", vosotros:"pensaréis", "ellos/ellas/ustedes":"pensarán"}},
{ infinitive:"pensar", translation:"to think", tense:"conditional",
  conjugations:{yo:"pensaría", tú:"pensarías", "él/ella/usted":"pensaría", nosotros:"pensaríamos", vosotros:"pensaríais", "ellos/ellas/ustedes":"pensarían"}},
{ infinitive:"pensar", translation:"to think", tense:"present perfect",
  conjugations:{yo:"he pensado", tú:"has pensado", "él/ella/usted":"ha pensado", nosotros:"hemos pensado", vosotros:"habéis pensado", "ellos/ellas/ustedes":"han pensado"}},
{ infinitive:"pensar", translation:"to think", tense:"pluscuamperfecto",
  conjugations:{yo:"había pensado", tú:"habías pensado", "él/ella/usted":"había pensado", nosotros:"habíamos pensado", vosotros:"habíais pensado", "ellos/ellas/ustedes":"habían pensado"}},
{ infinitive:"pensar", translation:"to think", tense:"future perfect",
  conjugations:{yo:"habré pensado", tú:"habrás pensado", "él/ella/usted":"habrá pensado", nosotros:"habremos pensado", vosotros:"habréis pensado", "ellos/ellas/ustedes":"habrán pensado"}},
{ infinitive:"pensar", translation:"to think", tense:"conditional perfect",
  conjugations:{yo:"habría pensado", tú:"habrías pensado", "él/ella/usted":"habría pensado", nosotros:"habríamos pensado", vosotros:"habríais pensado", "ellos/ellas/ustedes":"habrían pensado"}},
{ infinitive:"pensar", translation:"to think", tense:"present subjunctive",
  conjugations:{yo:"piense", tú:"pienses", "él/ella/usted":"piense", nosotros:"pensemos", vosotros:"penséis", "ellos/ellas/ustedes":"piensen"}},
{ infinitive:"pensar", translation:"to think", tense:"imperfect subjunctive",
  conjugations:{yo:"pensara", tú:"pensaras", "él/ella/usted":"pensara", nosotros:"pensáramos", vosotros:"pensarais", "ellos/ellas/ustedes":"pensaran"}},
{ infinitive:"pensar", translation:"to think", tense:"present perfect subjunctive",
  conjugations:{yo:"haya pensado", tú:"hayas pensado", "él/ella/usted":"haya pensado", nosotros:"hayamos pensado", vosotros:"hayáis pensado", "ellos/ellas/ustedes":"hayan pensado"}},
{ infinitive:"pensar", translation:"to think", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera pensado", tú:"hubieras pensado", "él/ella/usted":"hubiera pensado", nosotros:"hubiéramos pensado", vosotros:"hubierais pensado", "ellos/ellas/ustedes":"hubieran pensado"}}
// You can continue this pattern for the rest of the top 25 verbs:
  // ser, e
];
