const verbs = [
// HABLAR (to speak)
  { infinitive:"hablar", translation:"to speak", tense:"present",
    conjugations:{yo:"hablo", tú:"hablas", "él/ella/usted":"habla", nosotros:"hablamos", vosotros:"habláis", "ellos/ellas/ustedes":"hablan"}},
  { infinitive:"hablar", translation:"to speak", tense:"preterite",
    conjugations:{yo:"hablé", tú:"hablaste", "él/ella/usted":"habló", nosotros:"hablamos", vosotros:"hablasteis", "ellos/ellas/ustedes":"hablaron"}},
  { infinitive:"hablar", translation:"to speak", tense:"imperfect",
    conjugations:{yo:"hablaba", tú:"hablabas", "él/ella/usted":"hablaba", nosotros:"hablábamos", vosotros:"hablabais", "ellos/ellas/ustedes":"hablaban"}},
  { infinitive:"hablar", translation:"to speak", tense:"future",
    conjugations:{yo:"hablaré", tú:"hablarás", "él/ella/usted":"hablará", nosotros:"hablaremos", vosotros:"hablaréis", "ellos/ellas/ustedes":"hablarán"}},
  { infinitive:"hablar", translation:"to speak", tense:"conditional",
    conjugations:{yo:"hablaría", tú:"hablarías", "él/ella/usted":"hablaría", nosotros:"hablaríamos", vosotros:"hablaríais", "ellos/ellas/ustedes":"hablarían"}},
  { infinitive:"hablar", translation:"to speak", tense:"present perfect",
    conjugations:{yo:"he hablado", tú:"has hablado", "él/ella/usted":"ha hablado", nosotros:"hemos hablado", vosotros:"habéis hablado", "ellos/ellas/ustedes":"han hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"pluscuamperfecto",
    conjugations:{yo:"había hablado", tú:"habías hablado", "él/ella/usted":"había hablado", nosotros:"habíamos hablado", vosotros:"habíais hablado", "ellos/ellas/ustedes":"habían hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"future perfect",
    conjugations:{yo:"habré hablado", tú:"habrás hablado", "él/ella/usted":"habrá hablado", nosotros:"habremos hablado", vosotros:"habréis hablado", "ellos/ellas/ustedes":"habrán hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"conditional perfect",
    conjugations:{yo:"habría hablado", tú:"habrías hablado", "él/ella/usted":"habría hablado", nosotros:"habríamos hablado", vosotros:"habríais hablado", "ellos/ellas/ustedes":"habrían hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"present subjunctive",
    conjugations:{yo:"hable", tú:"hables", "él/ella/usted":"hable", nosotros:"hablemos", vosotros:"habléis", "ellos/ellas/ustedes":"hablen"}},
  { infinitive:"hablar", translation:"to speak", tense:"imperfect subjunctive",
    conjugations:{yo:"hablara", tú:"hablaras", "él/ella/usted":"hablara", nosotros:"habláramos", vosotros:"hablarais", "ellos/ellas/ustedes":"hablaran"}},
  { infinitive:"hablar", translation:"to speak", tense:"present perfect subjunctive",
    conjugations:{yo:"haya hablado", tú:"hayas hablado", "él/ella/usted":"haya hablado", nosotros:"hayamos hablado", vosotros:"hayáis hablado", "ellos/ellas/ustedes":"hayan hablado"}},
  { infinitive:"hablar", translation:"to speak", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera hablado", tú:"hubieras hablado", "él/ella/usted":"hubiera hablado", nosotros:"hubiéramos hablado", vosotros:"hubierais hablado", "ellos/ellas/ustedes":"hubieran hablado"}},

  // COMER (to eat)
  { infinitive:"comer", translation:"to eat", tense:"present",
    conjugations:{yo:"como", tú:"comes", "él/ella/usted":"come", nosotros:"comemos", vosotros:"coméis", "ellos/ellas/ustedes":"comen"}},
  { infinitive:"comer", translation:"to eat", tense:"preterite",
    conjugations:{yo:"comí", tú:"comiste", "él/ella/usted":"comió", nosotros:"comimos", vosotros:"comisteis", "ellos/ellas/ustedes":"comieron"}},
  { infinitive:"comer", translation:"to eat", tense:"imperfect",
    conjugations:{yo:"comía", tú:"comías", "él/ella/usted":"comía", nosotros:"comíamos", vosotros:"comíais", "ellos/ellas/ustedes":"comían"}},
  { infinitive:"comer", translation:"to eat", tense:"future",
    conjugations:{yo:"comeré", tú:"comerás", "él/ella/usted":"comerá", nosotros:"comeremos", vosotros:"comeréis", "ellos/ellas/ustedes":"comerán"}},
  { infinitive:"comer", translation:"to eat", tense:"conditional",
    conjugations:{yo:"comería", tú:"comerías", "él/ella/usted":"comería", nosotros:"comeríamos", vosotros:"comeríais", "ellos/ellas/ustedes":"comerían"}},
  { infinitive:"comer", translation:"to eat", tense:"present perfect",
    conjugations:{yo:"he comido", tú:"has comido", "él/ella/usted":"ha comido", nosotros:"hemos comido", vosotros:"habéis comido", "ellos/ellas/ustedes":"han comido"}},
  { infinitive:"comer", translation:"to eat", tense:"pluscuamperfecto",
    conjugations:{yo:"había comido", tú:"habías comido", "él/ella/usted":"había comido", nosotros:"habíamos comido", vosotros:"habíais comido", "ellos/ellas/ustedes":"habían comido"}},
  { infinitive:"comer", translation:"to eat", tense:"future perfect",
    conjugations:{yo:"habré comido", tú:"habrás comido", "él/ella/usted":"habrá comido", nosotros:"habremos comido", vosotros:"habréis comido", "ellos/ellas/ustedes":"habrán comido"}},
  { infinitive:"comer", translation:"to eat", tense:"conditional perfect",
    conjugations:{yo:"habría comido", tú:"habrías comido", "él/ella/usted":"habría comido", nosotros:"habríamos comido", vosotros:"habríais comido", "ellos/ellas/ustedes":"habrían comido"}},
  { infinitive:"comer", translation:"to eat", tense:"present subjunctive",
    conjugations:{yo:"coma", tú:"comas", "él/ella/usted":"coma", nosotros:"comamos", vosotros:"comáis", "ellos/ellas/ustedes":"coman"}},
  { infinitive:"comer", translation:"to eat", tense:"imperfect subjunctive",
    conjugations:{yo:"comiera", tú:"comieras", "él/ella/usted":"comiera", nosotros:"comiéramos", vosotros:"comierais", "ellos/ellas/ustedes":"comieran"}},
  { infinitive:"comer", translation:"to eat", tense:"present perfect subjunctive",
    conjugations:{yo:"haya comido", tú:"hayas comido", "él/ella/usted":"haya comido", nosotros:"hayamos comido", vosotros:"hayáis comido", "ellos/ellas/ustedes":"hayan comido"}},
  { infinitive:"comer", translation:"to eat", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera comido", tú:"hubieras comido", "él/ella/usted":"hubiera comido", nosotros:"hubiéramos comido", vosotros:"hubierais comido", "ellos/ellas/ustedes":"hubieran comido"}},

  // VIVIR (to live)
  { infinitive:"vivir", translation:"to live", tense:"present",
    conjugations:{yo:"vivo", tú:"vives", "él/ella/usted":"vive", nosotros:"vivimos", vosotros:"vivís", "ellos/ellas/ustedes":"viven"}},
  { infinitive:"vivir", translation:"to live", tense:"preterite",
    conjugations:{yo:"viví", tú:"viviste", "él/ella/usted":"vivió", nosotros:"vivimos", vosotros:"vivisteis", "ellos/ellas/ustedes":"vivieron"}},
  { infinitive:"vivir", translation:"to live", tense:"imperfect",
    conjugations:{yo:"vivía", tú:"vivías", "él/ella/usted":"vivía", nosotros:"vivíamos", vosotros:"vivíais", "ellos/ellas/ustedes":"vivían"}},
  { infinitive:"vivir", translation:"to live", tense:"future",
    conjugations:{yo:"viviré", tú:"vivirás", "él/ella/usted":"vivirá", nosotros:"viviremos", vosotros:"viviréis", "ellos/ellas/ustedes":"vivirán"}},
  { infinitive:"vivir", translation:"to live", tense:"conditional",
    conjugations:{yo:"viviría", tú:"vivirías", "él/ella/usted":"viviría", nosotros:"viviríamos", vosotros:"viviríais", "ellos/ellas/ustedes":"vivirían"}},
  { infinitive:"vivir", translation:"to live", tense:"present perfect",
    conjugations:{yo:"he vivido", tú:"has vivido", "él/ella/usted":"ha vivido", nosotros:"hemos vivido", vosotros:"habéis vivido", "ellos/ellas/ustedes":"han vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"pluscuamperfecto",
    conjugations:{yo:"había vivido", tú:"habías vivido", "él/ella/usted":"había vivido", nosotros:"habíamos vivido", vosotros:"habíais vivido", "ellos/ellas/ustedes":"habían vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"future perfect",
    conjugations:{yo:"habré vivido", tú:"habrás vivido", "él/ella/usted":"habrá vivido", nosotros:"habremos vivido", vosotros:"habréis vivido", "ellos/ellas/ustedes":"habrán vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"conditional perfect",
    conjugations:{yo:"habría vivido", tú:"habrías vivido", "él/ella/usted":"habría vivido", nosotros:"habríamos vivido", vosotros:"habríais vivido", "ellos/ellas/ustedes":"habrían vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"present subjunctive",
    conjugations:{yo:"viva", tú:"vivas", "él/ella/usted":"viva", nosotros:"vivamos", vosotros:"viváis", "ellos/ellas/ustedes":"vivan"}},
  { infinitive:"vivir", translation:"to live", tense:"imperfect subjunctive",
    conjugations:{yo:"viviera", tú:"vivieras", "él/ella/usted":"viviera", nosotros:"viviéramos", vosotros:"vivierais", "ellos/ellas/ustedes":"vivieran"}},
  { infinitive:"vivir", translation:"to live", tense:"present perfect subjunctive",
    conjugations:{yo:"haya vivido", tú:"hayas vivido", "él/ella/usted":"haya vivido", nosotros:"hayamos vivido", vosotros:"hayáis vivido", "ellos/ellas/ustedes":"hayan vivido"}},
  { infinitive:"vivir", translation:"to live", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera vivido", tú:"hubieras vivido", "él/ella/usted":"hubiera vivido", nosotros:"hubiéramos vivido", vosotros:"hubierais vivido", "ellos/ellas/ustedes":"hubieran vivido"}},

    // SER (to be)
  { infinitive:"ser", translation:"to be", tense:"present",
    conjugations:{yo:"soy", tú:"eres", "él/ella/usted":"es", nosotros:"somos", vosotros:"sois", "ellos/ellas/ustedes":"son"}},
  { infinitive:"ser", translation:"to be", tense:"preterite",
    conjugations:{yo:"fui", tú:"fuiste", "él/ella/usted":"fue", nosotros:"fuimos", vosotros:"fuisteis", "ellos/ellas/ustedes":"fueron"}},
  { infinitive:"ser", translation:"to be", tense:"imperfect",
    conjugations:{yo:"era", tú:"eras", "él/ella/usted":"era", nosotros:"éramos", vosotros:"erais", "ellos/ellas/ustedes":"eran"}},
  { infinitive:"ser", translation:"to be", tense:"future",
    conjugations:{yo:"seré", tú:"serás", "él/ella/usted":"será", nosotros:"seremos", vosotros:"seréis", "ellos/ellas/ustedes":"serán"}},
  { infinitive:"ser", translation:"to be", tense:"conditional",
    conjugations:{yo:"sería", tú:"serías", "él/ella/usted":"sería", nosotros:"seríamos", vosotros:"seríais", "ellos/ellas/ustedes":"serían"}},
  { infinitive:"ser", translation:"to be", tense:"present perfect",
    conjugations:{yo:"he sido", tú:"has sido", "él/ella/usted":"ha sido", nosotros:"hemos sido", vosotros:"habéis sido", "ellos/ellas/ustedes":"han sido"}},
  { infinitive:"ser", translation:"to be", tense:"pluscuamperfecto",
    conjugations:{yo:"había sido", tú:"habías sido", "él/ella/usted":"había sido", nosotros:"habíamos sido", vosotros:"habíais sido", "ellos/ellas/ustedes":"habían sido"}},
  { infinitive:"ser", translation:"to be", tense:"future perfect",
    conjugations:{yo:"habré sido", tú:"habrás sido", "él/ella/usted":"habrá sido", nosotros:"habremos sido", vosotros:"habréis sido", "ellos/ellas/ustedes":"habrán sido"}},
  { infinitive:"ser", translation:"to be", tense:"conditional perfect",
    conjugations:{yo:"habría sido", tú:"habrías sido", "él/ella/usted":"habría sido", nosotros:"habríamos sido", vosotros:"habríais sido", "ellos/ellas/ustedes":"habrían sido"}},
  { infinitive:"ser", translation:"to be", tense:"present subjunctive",
    conjugations:{yo:"sea", tú:"seas", "él/ella/usted":"sea", nosotros:"seamos", vosotros:"seáis", "ellos/ellas/ustedes":"sean"}},
  { infinitive:"ser", translation:"to be", tense:"imperfect subjunctive",
    conjugations:{yo:"fuera", tú:"fueras", "él/ella/usted":"fuera", nosotros:"fuéramos", vosotros:"fuerais", "ellos/ellas/ustedes":"fueran"}},
  { infinitive:"ser", translation:"to be", tense:"present perfect subjunctive",
    conjugations:{yo:"haya sido", tú:"hayas sido", "él/ella/usted":"haya sido", nosotros:"hayamos sido", vosotros:"hayáis sido", "ellos/ellas/ustedes":"hayan sido"}},
  { infinitive:"ser", translation:"to be", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera sido", tú:"hubieras sido", "él/ella/usted":"hubiera sido", nosotros:"hubiéramos sido", vosotros:"hubierais sido", "ellos/ellas/ustedes":"hubieran sido"}},

  // ESTAR (to be)
  { infinitive:"estar", translation:"to be", tense:"present",
    conjugations:{yo:"estoy", tú:"estás", "él/ella/usted":"está", nosotros:"estamos", vosotros:"estáis", "ellos/ellas/ustedes":"están"}},
  { infinitive:"estar", translation:"to be", tense:"preterite",
    conjugations:{yo:"estuve", tú:"estuviste", "él/ella/usted":"estuvo", nosotros:"estuvimos", vosotros:"estuvisteis", "ellos/ellas/ustedes":"estuvieron"}},
  { infinitive:"estar", translation:"to be", tense:"imperfect",
    conjugations:{yo:"estaba", tú:"estabas", "él/ella/usted":"estaba", nosotros:"estábamos", vosotros:"estabais", "ellos/ellas/ustedes":"estaban"}},
  { infinitive:"estar", translation:"to be", tense:"future",
    conjugations:{yo:"estaré", tú:"estarás", "él/ella/usted":"estará", nosotros:"estaremos", vosotros:"estaréis", "ellos/ellas/ustedes":"estarán"}},
  { infinitive:"estar", translation:"to be", tense:"conditional",
    conjugations:{yo:"estaría", tú:"estarías", "él/ella/usted":"estaría", nosotros:"estaríamos", vosotros:"estaríais", "ellos/ellas/ustedes":"estarían"}},
  { infinitive:"estar", translation:"to be", tense:"present perfect",
    conjugations:{yo:"he estado", tú:"has estado", "él/ella/usted":"ha estado", nosotros:"hemos estado", vosotros:"habéis estado", "ellos/ellas/ustedes":"han estado"}},
  { infinitive:"estar", translation:"to be", tense:"pluscuamperfecto",
    conjugations:{yo:"había estado", tú:"habías estado", "él/ella/usted":"había estado", nosotros:"habíamos estado", vosotros:"habíais estado", "ellos/ellas/ustedes":"habían estado"}},
  { infinitive:"estar", translation:"to be", tense:"future perfect",
    conjugations:{yo:"habré estado", tú:"habrás estado", "él/ella/usted":"habrá estado", nosotros:"habremos estado", vosotros:"habréis estado", "ellos/ellas/ustedes":"habrán estado"}},
  { infinitive:"estar", translation:"to be", tense:"conditional perfect",
    conjugations:{yo:"habría estado", tú:"habrías estado", "él/ella/usted":"habría estado", nosotros:"habríamos estado", vosotros:"habríais estado", "ellos/ellas/ustedes":"habrían estado"}},
  { infinitive:"estar", translation:"to be", tense:"present subjunctive",
    conjugations:{yo:"esté", tú:"estés", "él/ella/usted":"esté", nosotros:"estemos", vosotros:"estéis", "ellos/ellas/ustedes":"estén"}},
  { infinitive:"estar", translation:"to be", tense:"imperfect subjunctive",
    conjugations:{yo:"estuviera", tú:"estuvieras", "él/ella/usted":"estuviera", nosotros:"estuviéramos", vosotros:"estuvierais", "ellos/ellas/ustedes":"estuvieran"}},
  { infinitive:"estar", translation:"to be", tense:"present perfect subjunctive",
    conjugations:{yo:"haya estado", tú:"hayas estado", "él/ella/usted":"haya estado", nosotros:"hayamos estado", vosotros:"hayáis estado", "ellos/ellas/ustedes":"hayan estado"}},
  { infinitive:"estar", translation:"to be", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera estado", tú:"hubieras estado", "él/ella/usted":"hubiera estado", nosotros:"hubiéramos estado", vosotros:"hubierais estado", "ellos/ellas/ustedes":"hubieran estado"}},

  // TENER (to have)
  { infinitive:"tener", translation:"to have", tense:"present",
    conjugations:{yo:"tengo", tú:"tienes", "él/ella/usted":"tiene", nosotros:"tenemos", vosotros:"tenéis", "ellos/ellas/ustedes":"tienen"}},
  { infinitive:"tener", translation:"to have", tense:"preterite",
    conjugations:{yo:"tuve", tú:"tuviste", "él/ella/usted":"tuvo", nosotros:"tuvimos", vosotros:"tuvisteis", "ellos/ellas/ustedes":"tuvieron"}},
  { infinitive:"tener", translation:"to have", tense:"imperfect",
    conjugations:{yo:"tenía", tú:"tenías", "él/ella/usted":"tenía", nosotros:"teníamos", vosotros:"teníais", "ellos/ellas/ustedes":"tenían"}},
  { infinitive:"tener", translation:"to have", tense:"future",
    conjugations:{yo:"tendré", tú:"tendrás", "él/ella/usted":"tendrá", nosotros:"tendremos", vosotros:"tendréis", "ellos/ellas/ustedes":"tendrán"}},
  { infinitive:"tener", translation:"to have", tense:"conditional",
    conjugations:{yo:"tendría", tú:"tendrías", "él/ella/usted":"tendría", nosotros:"tendríamos", vosotros:"tendríais", "ellos/ellas/ustedes":"tendrían"}},
  { infinitive:"tener", translation:"to have", tense:"present perfect",
    conjugations:{yo:"he tenido", tú:"has tenido", "él/ella/usted":"ha tenido", nosotros:"hemos tenido", vosotros:"habéis tenido", "ellos/ellas/ustedes":"han tenido"}},
  { infinitive:"tener", translation:"to have", tense:"pluscuamperfecto",
    conjugations:{yo:"había tenido", tú:"habías tenido", "él/ella/usted":"había tenido", nosotros:"habíamos tenido", vosotros:"habíais tenido", "ellos/ellas/ustedes":"habían tenido"}},
  { infinitive:"tener", translation:"to have", tense:"future perfect",
    conjugations:{yo:"habré tenido", tú:"habrás tenido", "él/ella/usted":"habrá tenido", nosotros:"habremos tenido", vosotros:"habréis tenido", "ellos/ellas/ustedes":"habrán tenido"}},
  { infinitive:"tener", translation:"to have", tense:"conditional perfect",
    conjugations:{yo:"habría tenido", tú:"habrías tenido", "él/ella/usted":"habría tenido", nosotros:"habríamos tenido", vosotros:"habríais tenido", "ellos/ellas/ustedes":"habrían tenido"}},
  { infinitive:"tener", translation:"to have", tense:"present subjunctive",
    conjugations:{yo:"tenga", tú:"tengas", "él/ella/usted":"tenga", nosotros:"tengamos", vosotros:"tengáis", "ellos/ellas/ustedes":"tengan"}},
  { infinitive:"tener", translation:"to have", tense:"imperfect subjunctive",
    conjugations:{yo:"tuviera", tú:"tuvieras", "él/ella/usted":"tuviera", nosotros:"tuviéramos", vosotros:"tuvierais", "ellos/ellas/ustedes":"tuvieran"}},
  { infinitive:"tener", translation:"to have", tense:"present perfect subjunctive",
    conjugations:{yo:"haya tenido", tú:"hayas tenido", "él/ella/usted":"haya tenido", nosotros:"hayamos tenido", vosotros:"hayáis tenido", "ellos/ellas/ustedes":"hayan tenido"}},
  { infinitive:"tener", translation:"to have", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera tenido", tú:"hubieras tenido", "él/ella/usted":"hubiera tenido", nosotros:"hubiéramos tenido", vosotros:"hubierais tenido", "ellos/ellas/ustedes":"hubieran tenido"}},

  // IR (to go)
  { infinitive:"ir", translation:"to go", tense:"present",
    conjugations:{yo:"voy", tú:"vas", "él/ella/usted":"va", nosotros:"vamos", vosotros:"vais", "ellos/ellas/ustedes":"van"}},
  { infinitive:"ir", translation:"to go", tense:"preterite",
    conjugations:{yo:"fui", tú:"fuiste", "él/ella/usted":"fue", nosotros:"fuimos", vosotros:"fuisteis", "ellos/ellas/ustedes":"fueron"}},
  { infinitive:"ir", translation:"to go", tense:"imperfect",
    conjugations:{yo:"iba", tú:"ibas", "él/ella/usted":"iba", nosotros:"íbamos", vosotros:"ibais", "ellos/ellas/ustedes":"iban"}},
  { infinitive:"ir", translation:"to go", tense:"future",
    conjugations:{yo:"iré", tú:"irás", "él/ella/usted":"irá", nosotros:"iremos", vosotros:"iréis", "ellos/ellas/ustedes":"irán"}},
  { infinitive:"ir", translation:"to go", tense:"conditional",
    conjugations:{yo:"iría", tú:"irías", "él/ella/usted":"iría", nosotros:"iríamos", vosotros:"iríais", "ellos/ellas/ustedes":"irían"}},
  { infinitive:"ir", translation:"to go", tense:"present perfect",
    conjugations:{yo:"he ido", tú:"has ido", "él/ella/usted":"ha ido", nosotros:"hemos ido", vosotros:"habéis ido", "ellos/ellas/ustedes":"han ido"}},
  { infinitive:"ir", translation:"to go", tense:"pluscuamperfecto",
    conjugations:{yo:"había ido", tú:"habías ido", "él/ella/usted":"había ido", nosotros:"habíamos ido", vosotros:"habíais ido", "ellos/ellas/ustedes":"habían ido"}},
  { infinitive:"ir", translation:"to go", tense:"future perfect",
    conjugations:{yo:"habré ido", tú:"habrás ido", "él/ella/usted":"habrá ido", nosotros:"habremos ido", vosotros:"habréis ido", "ellos/ellas/ustedes":"habrán ido"}},
  { infinitive:"ir", translation:"to go", tense:"conditional perfect",
    conjugations:{yo:"habría ido", tú:"habrías ido", "él/ella/usted":"habría ido", nosotros:"habríamos ido", vosotros:"habríais ido", "ellos/ellas/ustedes":"habrían ido"}},
  { infinitive:"ir", translation:"to go", tense:"present subjunctive",
    conjugations:{yo:"vaya", tú:"vayas", "él/ella/usted":"vaya", nosotros:"vayamos", vosotros:"vayáis", "ellos/ellas/ustedes":"vayan"}},
  { infinitive:"ir", translation:"to go", tense:"imperfect subjunctive",
    conjugations:{yo:"fuera", tú:"fueras", "él/ella/usted":"fuera", nosotros:"fuéramos", vosotros:"fuerais", "ellos/ellas/ustedes":"fueran"}},
  { infinitive:"ir", translation:"to go", tense:"present perfect subjunctive",
    conjugations:{yo:"haya ido", tú:"hayas ido", "él/ella/usted":"haya ido", nosotros:"hayamos ido", vosotros:"hayáis ido", "ellos/ellas/ustedes":"hayan ido"}},
  { infinitive:"ir", translation:"to go", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera ido", tú:"hubieras ido", "él/ella/usted":"hubiera ido", nosotros:"hubiéramos ido", vosotros:"hubierais ido", "ellos/ellas/ustedes":"hubieran ido"}},

  // HACER (to do/make)
  { infinitive:"hacer", translation:"to do/make", tense:"present",
    conjugations:{yo:"hago", tú:"haces", "él/ella/usted":"hace", nosotros:"hacemos", vosotros:"hacéis", "ellos/ellas/ustedes":"hacen"}},
  { infinitive:"hacer", translation:"to do/make", tense:"preterite",
    conjugations:{yo:"hice", tú:"hiciste", "él/ella/usted":"hizo", nosotros:"hicimos", vosotros:"hicisteis", "ellos/ellas/ustedes":"hicieron"}},
  { infinitive:"hacer", translation:"to do/make", tense:"imperfect",
    conjugations:{yo:"hacía", tú:"hacías", "él/ella/usted":"hacía", nosotros:"hacíamos", vosotros:"hacíais", "ellos/ellas/ustedes":"hacían"}},
  { infinitive:"hacer", translation:"to do/make", tense:"future",
    conjugations:{yo:"haré", tú:"harás", "él/ella/usted":"hará", nosotros:"haremos", vosotros:"haréis", "ellos/ellas/ustedes":"harán"}},
  { infinitive:"hacer", translation:"to do/make", tense:"conditional",
    conjugations:{yo:"haría", tú:"harías", "él/ella/usted":"haría", nosotros:"haríamos", vosotros:"haríais", "ellos/ellas/ustedes":"harían"}},
  { infinitive:"hacer", translation:"to do/make", tense:"present perfect",
    conjugations:{yo:"he hecho", tú:"has hecho", "él/ella/usted":"ha hecho", nosotros:"hemos hecho", vosotros:"habéis hecho", "ellos/ellas/ustedes":"han hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"pluscuamperfecto",
    conjugations:{yo:"había hecho", tú:"habías hecho", "él/ella/usted":"había hecho", nosotros:"habíamos hecho", vosotros:"habíais hecho", "ellos/ellas/ustedes":"habían hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"future perfect",
    conjugations:{yo:"habré hecho", tú:"habrás hecho", "él/ella/usted":"habrá hecho", nosotros:"habremos hecho", vosotros:"habréis hecho", "ellos/ellas/ustedes":"habrán hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"conditional perfect",
    conjugations:{yo:"habría hecho", tú:"habrías hecho", "él/ella/usted":"habría hecho", nosotros:"habríamos hecho", vosotros:"habríais hecho", "ellos/ellas/ustedes":"habrían hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"present subjunctive",
    conjugations:{yo:"haga", tú:"hagas", "él/ella/usted":"haga", nosotros:"hagamos", vosotros:"hagáis", "ellos/ellas/ustedes":"hagan"}},
  { infinitive:"hacer", translation:"to do/make", tense:"imperfect subjunctive",
    conjugations:{yo:"hiciera", tú:"hicieras", "él/ella/usted":"hiciera", nosotros:"hiciéramos", vosotros:"hicierais", "ellos/ellas/ustedes":"hicieran"}},
  { infinitive:"hacer", translation:"to do/make", tense:"present perfect subjunctive",
    conjugations:{yo:"haya hecho", tú:"hayas hecho", "él/ella/usted":"haya hecho", nosotros:"hayamos hecho", vosotros:"hayáis hecho", "ellos/ellas/ustedes":"hayan hecho"}},
  { infinitive:"hacer", translation:"to do/make", tense:"past perfect subjunctive",
    conjugations:{yo:"hubiera hecho", tú:"hubieras hecho", "él/ella/usted":"hubiera hecho", nosotros:"hubiéramos hecho", vosotros:"hubierais hecho", "ellos/ellas/ustedes":"hubieran hecho"}},

  { infinitive:"poder", translation:"to be able", tense:"present",
  conjugations:{yo:"puedo", tú:"puedes", "él/ella/usted":"puede", nosotros:"podemos", vosotros:"podéis", "ellos/ellas/ustedes":"pueden"}},
{ infinitive:"poder", translation:"to be able", tense:"preterite",
  conjugations:{yo:"pude", tú:"pudiste", "él/ella/usted":"pudo", nosotros:"pudimos", vosotros:"pudisteis", "ellos/ellas/ustedes":"pudieron"}},
{ infinitive:"poder", translation:"to be able", tense:"imperfect",
  conjugations:{yo:"podía", tú:"podías", "él/ella/usted":"podía", nosotros:"podíamos", vosotros:"podíais", "ellos/ellas/ustedes":"podían"}},
{ infinitive:"poder", translation:"to be able", tense:"future",
  conjugations:{yo:"podré", tú:"podrás", "él/ella/usted":"podrá", nosotros:"podremos", vosotros:"podréis", "ellos/ellas/ustedes":"podrán"}},
{ infinitive:"poder", translation:"to be able", tense:"conditional",
  conjugations:{yo:"podría", tú:"podrías", "él/ella/usted":"podría", nosotros:"podríamos", vosotros:"podríais", "ellos/ellas/ustedes":"podrían"}},
{ infinitive:"poder", translation:"to be able", tense:"present perfect",
  conjugations:{yo:"he podido", tú:"has podido", "él/ella/usted":"ha podido", nosotros:"hemos podido", vosotros:"habéis podido", "ellos/ellas/ustedes":"han podido"}},
{ infinitive:"poder", translation:"to be able", tense:"pluscuamperfecto",
  conjugations:{yo:"había podido", tú:"habías podido", "él/ella/usted":"había podido", nosotros:"habíamos podido", vosotros:"habíais podido", "ellos/ellas/ustedes":"habían podido"}},
{ infinitive:"poder", translation:"to be able", tense:"future perfect",
  conjugations:{yo:"habré podido", tú:"habrás podido", "él/ella/usted":"habrá podido", nosotros:"habremos podido", vosotros:"habréis podido", "ellos/ellas/ustedes":"habrán podido"}},
{ infinitive:"poder", translation:"to be able", tense:"conditional perfect",
  conjugations:{yo:"habría podido", tú:"habrías podido", "él/ella/usted":"habría podido", nosotros:"habríamos podido", vosotros:"habríais podido", "ellos/ellas/ustedes":"habrían podido"}},
{ infinitive:"poder", translation:"to be able", tense:"present subjunctive",
  conjugations:{yo:"pueda", tú:"puedas", "él/ella/usted":"pueda", nosotros:"podamos", vosotros:"podáis", "ellos/ellas/ustedes":"puedan"}},
{ infinitive:"poder", translation:"to be able", tense:"imperfect subjunctive",
  conjugations:{yo:"pudiera", tú:"pudieras", "él/ella/usted":"pudiera", nosotros:"pudiéramos", vosotros:"pudierais", "ellos/ellas/ustedes":"pudieran"}},
{ infinitive:"poder", translation:"to be able", tense:"present perfect subjunctive",
  conjugations:{yo:"haya podido", tú:"hayas podido", "él/ella/usted":"haya podido", nosotros:"hayamos podido", vosotros:"hayáis podido", "ellos/ellas/ustedes":"hayan podido"}},
{ infinitive:"poder", translation:"to be able", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera podido", tú:"hubieras podido", "él/ella/usted":"hubiera podido", nosotros:"hubiéramos podido", vosotros:"hubierais podido", "ellos/ellas/ustedes":"hubieran podido"}},

// DECIR (to say / tell)
{ infinitive:"decir", translation:"to say", tense:"present",
  conjugations:{yo:"digo", tú:"dices", "él/ella/usted":"dice", nosotros:"decimos", vosotros:"decís", "ellos/ellas/ustedes":"dicen"}},
{ infinitive:"decir", translation:"to say", tense:"preterite",
  conjugations:{yo:"dije", tú:"dijiste", "él/ella/usted":"dijo", nosotros:"dijimos", vosotros:"dijisteis", "ellos/ellas/ustedes":"dijeron"}},
{ infinitive:"decir", translation:"to say", tense:"imperfect",
  conjugations:{yo:"decía", tú:"decías", "él/ella/usted":"decía", nosotros:"decíamos", vosotros:"decíais", "ellos/ellas/ustedes":"decían"}},
{ infinitive:"decir", translation:"to say", tense:"future",
  conjugations:{yo:"diré", tú:"dirás", "él/ella/usted":"dirá", nosotros:"diremos", vosotros:"diréis", "ellos/ellas/ustedes":"dirán"}},
{ infinitive:"decir", translation:"to say", tense:"conditional",
  conjugations:{yo:"diría", tú:"dirías", "él/ella/usted":"diría", nosotros:"diríamos", vosotros:"diríais", "ellos/ellas/ustedes":"dirían"}},
{ infinitive:"decir", translation:"to say", tense:"present perfect",
  conjugations:{yo:"he dicho", tú:"has dicho", "él/ella/usted":"ha dicho", nosotros:"hemos dicho", vosotros:"habéis dicho", "ellos/ellas/ustedes":"han dicho"}},
{ infinitive:"decir", translation:"to say", tense:"pluscuamperfecto",
  conjugations:{yo:"había dicho", tú:"habías dicho", "él/ella/usted":"había dicho", nosotros:"habíamos dicho", vosotros:"habíais dicho", "ellos/ellas/ustedes":"habían dicho"}},
{ infinitive:"decir", translation:"to say", tense:"future perfect",
  conjugations:{yo:"habré dicho", tú:"habrás dicho", "él/ella/usted":"habrá dicho", nosotros:"habremos dicho", vosotros:"habréis dicho", "ellos/ellas/ustedes":"habrán dicho"}},
{ infinitive:"decir", translation:"to say", tense:"conditional perfect",
  conjugations:{yo:"habría dicho", tú:"habrías dicho", "él/ella/usted":"habría dicho", nosotros:"habríamos dicho", vosotros:"habríais dicho", "ellos/ellas/ustedes":"habrían dicho"}},
{ infinitive:"decir", translation:"to say", tense:"present subjunctive",
  conjugations:{yo:"diga", tú:"digas", "él/ella/usted":"diga", nosotros:"digamos", vosotros:"digáis", "ellos/ellas/ustedes":"digan"}},
{ infinitive:"decir", translation:"to say", tense:"imperfect subjunctive",
  conjugations:{yo:"dijera", tú:"dijeras", "él/ella/usted":"dijera", nosotros:"dijéramos", vosotros:"dijerais", "ellos/ellas/ustedes":"dijeran"}},
{ infinitive:"decir", translation:"to say", tense:"present perfect subjunctive",
  conjugations:{yo:"haya dicho", tú:"hayas dicho", "él/ella/usted":"haya dicho", nosotros:"hayamos dicho", vosotros:"hayáis dicho", "ellos/ellas/ustedes":"hayan dicho"}},
{ infinitive:"decir", translation:"to say", tense:"past perfect subjunctive",
  conjugations:{yo:"hubiera dicho", tú:"hubieras dicho", "él/ella/usted":"hubiera dicho", nosotros:"hubiéramos dicho", vosotros:"hubierais dicho", "ellos/ellas/ustedes":"hubieran dicho"}}

  
  // You can continue this pattern for the rest of the top 25 verbs:
  // ser, e
];
